### ISSUE TITLE
JD多合一签到错误

### ISSUE THREAD

**Issue by cangbai12** [6dylan6/jdpro#11]
开始执行 京东多合一签到 签到，请稍等...

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js
- /ql/scripts/6dylan6_jdpro/JD_DailyBonus.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js:10:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js',
    '/ql/scripts/6dylan6_jdpro/JD_DailyBonus.js'
  ]
}

Node.js v17.4.0
京东签到脚本执行异常:Error: Command failed: /usr/local/bin/node ./JD_DailyBonus.js >> ./result.txt
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js
- /ql/scripts/6dylan6_jdpro/JD_DailyBonus.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js:10:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js',
    '/ql/scripts/6dylan6_jdpro/JD_DailyBonus.js'
  ]
}

Node.js v17.4.0

有没有大佬给看一下，谢谢了

**Comment by Miroxyz** [comment]
Error: Cannot find module 'png-js'
缺少 png-js

**Comment by cangbai12** [comment]
okok，我弄好了，pnpm i png-js

**Comment by cangbai12** [comment]
> Error: Cannot find module 'png-js' 缺少 png-js

感谢感谢

**Comment by cangbai12** [comment]
> Error: Cannot find module 'png-js' 缺少 png-js

我才看到新增了依赖安装的任务，实在不好意思打扰您了
