### ISSUE TITLE
网络正正常，常规任务正常，某些临时活动脚本运行显示：sign获取失败,请检查网络！

### ISSUE THREAD

**Issue by wifisky-feilian** [6dylan6/jdpro#116]
******开始【京东账号1】XXXXXX *********

sign获取失败,重试...

read ECONNRESET
sign获取失败,请检查网络！

TypeError: Cannot read properties of undefined (reading 'body')
    at Object._0x19e405 [as getbody] (/ql/data/scripts/6dylan6_jdpro/function/dylanx.js:1:14576)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0xd4c415 (/ql/data/scripts/6dylan6_jdpro/function/dylank.js:1:38208)
    at async _0xb9522b (/ql/data/scripts/6dylan6_jdpro/jd_opencard1020.js:16:62448)
    at async /ql/data/scripts/6dylan6_jdpro/jd_opencard1020.js:16:49945
Token请求失败
获取Token失败

网络正正常，常规任务正常，某些临时活动脚本运行显示：sign获取失败,请检查网络！

**Comment by 6dylan6** [comment]
@wifisky-feilian 这是请求不通，你网络有防火墙限制吗

**Comment by wifisky-feilian** [comment]
> @wifisky-feilian 这是请求不通，你网络有防火墙限制吗
没有网络有防火墙限制，JD其它任务正常，主要是那些临时任务原来可以，现在就是sign获取失败,重试...read ECONNRESETsign获取失败,请检查网络，比如这些脚本就出现这些错误：d_dplh1022.js、jd_dplh1020B.js、jd_opencard1017.js等等类似临时活动脚本

**Comment by 6dylan6** [comment]
@wifisky-feilian 留个向日葵远程瞅瞅

**Comment by pittyuppie** [comment]
有解决办法了吗？我也遇到同样的问题了

**Comment by hanccy** [comment]
有解决办法了吗？我也遇到同样的问题了
