### ISSUE TITLE
众筹许愿池/京东生鲜 报错

### ISSUE THREAD

**Issue by gclm** [6dylan6/jdpro#12]
### 众筹许愿池
![image](https://user-images.githubusercontent.com/27618687/153532710-56cb5f39-2166-45aa-b495-879c90f1dbea.png)

```
TypeError: Cannot read properties of undefined (reading 'taskVos')
    at /ql/scripts/gclm_jds_main/jd_wish.js:154:60
    at got.post.then.message (/ql/scripts/gclm_jds_main/jd_wish.js:416:5772)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

❗️众筹许愿池, 错误!
TypeError: Cannot read properties of undefined (reading 'userInfo')
    at jd_wish (/ql/scripts/gclm_jds_main/jd_wish.js:121:76)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/gclm_jds_main/jd_wish.js:64:9
```

### 京东生鲜
```
🔔京东生鲜每日抽奖, 开始!

开始做浏览会场:品牌上新
任务成功
任务奖励领取成功
TypeError: Cannot read properties of null (reading 'itemName')
    at run (/ql/scripts/gclm_jds_main/jd_sxLottery.js:104:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async jdmodule (/ql/scripts/gclm_jds_main/jd_sxLottery.js:85:9)
    at async /ql/scripts/gclm_jds_main/jd_sxLottery.js:56:17
开始做浏览会场:金牌生鲜餐馆
任务成功
任务奖励领取成功
TypeError: Cannot read properties of null (reading 'itemName')
    at run (/ql/scripts/gclm_jds_main/jd_sxLottery.js:104:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async jdmodule (/ql/scripts/gclm_jds_main/jd_sxLottery.js:85:9)
    at async /ql/scripts/gclm_jds_main/jd_sxLottery.js:56:17
TypeError: Cannot read properties of null (reading 'itemName')
    at run (/ql/scripts/gclm_jds_main/jd_sxLottery.js:104:58)
    at jdmodule (/ql/scripts/gclm_jds_main/jd_sxLottery.js:85:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/gclm_jds_main/jd_sxLottery.js:56:17
开始抽奖
抽奖结果:null
抽奖结果:null
```

**Comment by gclm** [comment]
### 店铺签到
```
❗️店铺签到, 错误!
TypeError: Cannot read properties of undefined (reading 'venderId')
    at /ql/scripts/gclm_jds_main/jd_dpsign.js:161:30
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/gclm_jds_main/jd_dpsign.js:417:4791)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
【荣事达（Royalstar）两季品京东自营旗舰店】
```

**Comment by 6dylan6** [comment]
许愿池已更新，生鲜，店铺晚点更
