### ISSUE TITLE
自动评价失效

### ISSUE THREAD

**Issue by chenpipy** [6dylan6/jdpro#130]
自动评价貌似一直卡着，也不报错，请问是失效了吗？

**Comment by 6dylan6** [comment]
没有，我测正常。你换个号看看

**Comment by chenpipy** [comment]
![image](https://user-images.githubusercontent.com/23254344/162877953-805a4d35-d210-4ca1-8ba0-72d430447538.png)
失败的具体原因，好奇怪哦

**Comment by chenpipy** [comment]
自动评价现在又报错了
![image](https://user-images.githubusercontent.com/23254344/164745784-b68944ec-950f-4616-8fd6-8ab97e896d0e.png)

**Comment by 6dylan6** [comment]
奇怪，我这边正常呢。把日志底下的全贴上来，我看下

**Comment by gaojianpete** [comment]
开始商品与服务评价！
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 537, in <module>
    start()
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 522, in start
    ordinary(headers, f'账号{i}[{user}]')
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 402, in ordinary
    for i, da in enumerate(op(headers)):
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 342, in op
    data = req.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>
我得报错是这样的
