### ISSUE TITLE
健康社区兑换京豆

### ISSUE THREAD

**Issue by deadnessking** [6dylan6/jdpro#132]
## 开始执行... 2022-04-11 00:13:34

[2022-04-11 00:13:35]: 
xxxxxxxxxxxx
脚本默认兑换20豆，18W分以上才兑换，具体修改教程可看脚本开头注释
		【健康社区兑换-Python】
############# 开始############ 
Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_health_exchange.py", line 427, in <module>
    start ()
  File "/ql/data/scripts/6dylan6_jdpro/jd_health_exchange.py", line 404, in start
    cookiesList, userNameList, pinNameList = getCk.iscookie ()
  File "/ql/data/scripts/6dylan6_jdpro/jd_health_exchange.py", line 118, in iscookie
    if 'pt_key=' in cookies and 'pt_pin=' in cookies:
NameError: name 'cookies' is not defined

## 执行结束... 2022-04-11 00:13:35 耗时 1 秒

cookie我已经填了，其他脚本都正常，就这个出问题

**Comment by deadnessking** [comment]
另外领金贴是过期了吗

******开始【京东账号1】*********

获取签到状态成功 今日未签到 连续签到 0 天

签到成功 0
获取互动任务失败 渠道关闭

❗️领金贴, 错误!
TypeError: $.willTask is not iterable
    at doTask (/ql/data/scripts/6dylan6_jdpro/jd_jin_tie.js:394:22)
    at main (/ql/data/scripts/6dylan6_jdpro/jd_jin_tie.js:72:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/data/scripts/6dylan6_jdpro/jd_jin_tie.js:58:7

**Comment by deadnessking** [comment]
还有京东汽车 6dylan6_jdpro/jd_car.js

============脚本执行时间：2022/4/10 07:10:36=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

******开始【京东账号1】*********

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at safeGet (/ql/data/scripts/6dylan6_jdpro/jd_car.js:323:21)
    at /ql/data/scripts/6dylan6_jdpro/jd_car.js:89:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/6dylan6_jdpro/jd_car.js:344:4869)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
京东服务器访问数据为空，请检查自身设备网络情况

❗️京东汽车, 错误!
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/data/scripts/6dylan6_jdpro/jd_car.js:108:23
    at /ql/data/scripts/6dylan6_jdpro/jd_car.js:344:5858
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at safeGet (/ql/data/scripts/6dylan6_jdpro/jd_car.js:323:21)
    at /ql/data/scripts/6dylan6_jdpro/jd_car.js:137:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/6dylan6_jdpro/jd_car.js:344:4869)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
京东服务器访问数据为空，请检查自身设备网络情况
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at safeGet (/ql/data/scripts/6dylan6_jdpro/jd_car.js:323:21)
    at /ql/data/scripts/6dylan6_jdpro/jd_car.js:218:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/6dylan6_jdpro/jd_car.js:344:4869)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
京东服务器访问数据为空，请检查自身设备网络情况

**Comment by deadnessking** [comment]
jddj_fruit_collectWater.js
jddj_getPoints.js
京东到家果园水车收水滴任务脚本和京东到家鲜豆庄园收水滴脚本都是类似的问题

====================共3个京东账号Cookie=================

============脚本执行时间：2022/4/10 13:06:57=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>


★★★★★开始执行第1个账号,共3个账号★★★★★

【收水滴】:非法的操作

★★★★★开始执行第2个账号,共3个账号★★★★★

【收水滴】:非法的操作

★★★★★开始执行第3个账号,共3个账号★★★★★

【收水滴】:非法的操作
done!

**Comment by 6dylan6** [comment]
谢谢反馈，第一个我这边测试正常，你更新看下，第二个已修复 ，第三个活动已过期，第四个你手动进京东到家果园开通

**Comment by deadnessking** [comment]
> 谢谢反馈，第一个我这边测试正常，你更新看下，第二个已修复 ，第三个活动已过期，第四个你手动进京东到家果园开通

好的，多谢大佬

**Comment by gujiwuqing** [comment]
> 谢谢反馈，第一个我这边测试正常，你更新看下，第二个已修复 ，第三个活动已过期，第四个你手动进京东到家果园开通

老哥 想咨询
<img width="571" alt="image" src="https://user-images.githubusercontent.com/44566835/163190217-a8d2b614-f69c-4c56-afd6-ec2e6563db70.png">
 这种也是在变量填写吗？
