### ISSUE TITLE
旧东东农场，不能助力了 大佬

### ISSUE THREAD

**Issue by underlaw** [6dylan6/jdpro#141]
能收集助力码，都不能助力，新农场没问题

**Comment by 6dylan6** [comment]
@underlaw 最新版吗，在运行一次搜集助力码任务

**Comment by wifisky-feilian** [comment]
> 能收集助力码，都不能助力，新农场没问题



> @underlaw 最新版吗，在运行一次搜集助力码任务

是有问题（搜集助力码任务脚本默认运行时间0：15分，搜集到的助力码，不知道为什么到农场任务-助力时提示：>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

使用指定的助力码

没有助力码,请变量FRUITSHARECODES指定或执行农场任务自动收集助力码

🔔东东农场-助力, 结束! 🕛 1.053 秒），

临时解决办法：先看下东东农场-任务脚本运行时间点计划，看下农场助力脚本运行时间计划，把“搜集助力码任务”脚本运行时间比东东农场-任务计划时间点运行结束后时间晚几分钟上，比农场助力时间早几分钟，东东农场-任务和助力有几次计划（好像3次时间点），“搜集助力码任务”脚本计划就设置几次（也设置3次计划时间点）比东东农场-任务计划时间运行结束时间晚些时间，比农场助力并提前几分钟。

好像是“搜集助力码任务脚本”需要“东东农场-任务”运行后才能正常搜集到互助码，而“搜集助力码任务脚本”默认运行时间早于当天“东东农场-任务”脚本运行时间，所以就搜集不到账号的互助码造成的。

个人猜测，不知道还有其它原因没，只能靠大神解决了。

**Comment by 6dylan6** [comment]
@wifisky-feilian 这个问题已修复，更新就行

**Comment by wifisky-feilian** [comment]
> @wifisky-feilian 这个问题已修复，更新就行

你正好在线，我的问题给我远程看看：sign获取失败,重试...

read ECONNRESET
sign获取失败,请检查网络！

TypeError: Cannot read properties of undefined (reading 'body')
    at Object._0x63cb62 [as getbody] (/ql/data/scripts/6dylan6_jdpro/function/dylanx.js:1:11761)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x210264 (/ql/data/scripts/6dylan6_jdpro/function/dylank.js:1:24892)
    at async _0x2b19a8 (/ql/data/scripts/6dylan6_jdpro/function/dylank.js:1:29367)
    at async _0x5a9937 (/ql/data/scripts/6dylan6_jdpro/jd_opencard1101C.js:15:26725)
    at async /ql/data/scripts/6dylan6_jdpro/jd_opencard1101C.js:15:12981

**Comment by 6dylan6** [comment]
@wifisky-feilian 关闭ipv6试试

**Comment by wifisky-feilian** [comment]
> @wifisky-feilian 关闭ipv6试试
NAS的IPV6和上级路由器的IPV6都关闭了还是上面一样的错误提示
