### ISSUE TITLE
WxPusher一对一推送

### ISSUE THREAD

**Issue by Kevin-1273** [6dylan6/jdpro#142]
![aaa8a0ba68a9865109dcbcd89413b90](https://user-images.githubusercontent.com/74080924/163556092-9ec9c0a7-24db-49bc-93a9-fe25c73a9919.png)
配置文件里写了export WP_APP_TOKEN_ONE=
环境变量里的export WP_APP_TOKEN_ONE=也写了
![297ba175a6f2909f76e66fe50ed9db5](https://user-images.githubusercontent.com/74080924/163556318-e524ea92-e9f5-4e90-ba4f-070f23abd8ae.png)
一运行资产变动就找不到uid
![10ee31bd88cf2445696b54cad3504dc](https://user-images.githubusercontent.com/74080924/163556467-a26485d6-f9ee-4b44-a251-999a992b8242.png)
CK_WxPusherUid.json是写到这个位置吗

**Comment by Kevin-1273** [comment]
请问大佬这个咋弄啊

**Comment by 6dylan6** [comment]
你是多少版本的青龙。新版老板不一样

**Comment by Kevin-1273** [comment]
> 

2.12.0

**Comment by 6dylan6** [comment]
2.12放到/ql/data/scripts下面

**Comment by Kevin-1273** [comment]
好的我试试，感谢！

**Comment by ROOOCCCK** [comment]
老哥搞定了吗，我也在搞一对一WX，也是2.12.文件配置好了，❌ 京东资产统计, 失败! 原因: TypeError: notify.sendNotifybyWxPucher is not a function!
用资产是查到一个账号就提示这个

**Comment by 6dylan6** [comment]
> 老哥搞定了吗，我也在搞一对一WX，也是2.12.文件配置好了，❌ 京东资产统计, 失败! 原因: TypeError: notify.sendNotifybyWxPucher is not a function! 用资产是查到一个账号就提示这个

你这个是sendnotify.js被青龙默认的覆盖了。复制一份到deps目录

**Comment by ROOOCCCK** [comment]
> > 老哥搞定了吗，我也在搞一对一WX，也是2.12.文件配置好了，❌ 京东资产统计, 失败! 原因: TypeError: notify.sendNotifybyWxPucher is not a function! 用资产是查到一个账号就提示这个
> 
> 你这个是sendnotify.js被青龙默认的覆盖了。复制一份到deps目录

大佬，我刚按你的操作一边，还是不行，DEPS跟SCRIPTS都放一样的文件，124k。我如果把config关于WX推送变量注销，资产统计就可以正常运行，不知道是哪里出问题

**Comment by 6dylan6** [comment]
> > > 老哥搞定了吗，我也在搞一对一WX，也是2.12.文件配置好了，❌ 京东资产统计, 失败! 原因: TypeError: notify.sendNotifybyWxPucher is not a function! 用资产是查到一个账号就提示这个
> > 
> > 
> > 你这个是sendnotify.js被青龙默认的覆盖了。复制一份到deps目录
> 
> 大佬，我刚按你的操作一边，还是不行，DEPS跟SCRIPTS都放一样的文件，124k。我如果把config关于WX推送变量注销，资产统计就可以正常运行，不知道是哪里出问题

放到deps在拉下库

**Comment by ROOOCCCK** [comment]
> > > > 老哥搞定了吗，我也在搞一对一WX，也是2.12.文件配置好了，❌ 京东资产统计, 失败! 原因: TypeError: notify.sendNotifybyWxPucher is not a function! 用资产是查到一个账号就提示这个
> > > 
> > > 
> > > 你这个是sendnotify.js被青龙默认的覆盖了。复制一份到deps目录
> > 
> > 
> > 大佬，我刚按你的操作一边，还是不行，DEPS跟SCRIPTS都放一样的文件，124k。我如果把config关于WX推送变量注销，资产统计就可以正常运行，不知道是哪里出问题
> 
> 放到deps在拉下库

🔔京东资产统计, 开始!
undefined:7
]
^

SyntaxError: Unexpected token ] in JSON at position 173
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/sendNotify.js:170:26)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:11:29)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)

## 执行结束... 2022-04-30 11:46:57 耗时 1 秒

=-=

**Comment by 6dylan6** [comment]
？你改jd_bean_change文件了吗

**Comment by ROOOCCCK** [comment]
> 

没动过哦

**Comment by 6dylan6** [comment]
> > 
> 
> 没动过哦

CKName_cache.json检查里面格式。格式不对。

**Comment by 6dylan6** [comment]
> > > 
> > 
> > 
> > 没动过哦
> 
> CKName_cache.json检查里面格式。格式不对。

https://github.com/6dylan6/jdpro/blob/main/notify.md

**Comment by ROOOCCCK** [comment]
> > > 
> > 
> > 
> > 没动过哦
> 
> CKName_cache.json检查里面格式。格式不对。

在哪里的，没找到这个

> > > > 
> > > 
> > > 
> > > 没动过哦
> > 
> > 
> > CKName_cache.json检查里面格式。格式不对。
> 
> https://github.com/6dylan6/jdpro/blob/main/notify.md

我的没有CKName_cache.json这个文件，百度也不知道这个文件的格式是怎么样的

**Comment by ROOOCCCK** [comment]
> ？你改jd_bean_change文件了吗

CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有

**Comment by 6dylan6** [comment]
> > ？你改jd_bean_change文件了吗
> 
> CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有

说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号

**Comment by ROOOCCCK** [comment]
> > > ？你改jd_bean_change文件了吗
> > 
> > 
> > CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有
> 
> 说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号

[
{
"pt_pin": "pt_key=AAJiSlUlA**********DB; pt_pin=jd*********76;",
"Uid": "UID_UrcfWTF******YNeZe"
},
{
]

应该没少吧

**Comment by 6dylan6** [comment]
> > > > ？你改jd_bean_change文件了吗
> > > 
> > > 
> > > CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有
> > 
> > 
> > 说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号
> 
> [ { "pt_pin": "pt_key=AAJiSlUlA__********DB; pt_pin=jd********_76;", "Uid": "UID_UrcfWTF_*****YNeZe" }, { ]
> 
> 应该没少吧

多了,{

**Comment by ROOOCCCK** [comment]
> > > > > ？你改jd_bean_change文件了吗
> > > > 
> > > > 
> > > > CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有
> > > 
> > > 
> > > 说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号
> > 
> > 
> > [ { "pt_pin": "pt_key=AAJiSlUlA__********DB; pt_pin=jd********_76;", "Uid": "UID_UrcfWTF_*****YNeZe" }, { ]
> > 应该没少吧
> 
> 多了,{

正在从CK_WxPusherUid文件中检索资料...
未查询到用户的Uid,取消一对一通知发送...

现在脚本能运行，但是跟题主一样报这个错==！

**Comment by 6dylan6** [comment]
> > > > > > ？你改jd_bean_change文件了吗
> > > > > 
> > > > > 
> > > > > CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有
> > > > 
> > > > 
> > > > 说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号
> > > 
> > > 
> > > [ { "pt_pin": "pt_key=AAJiSlUlA__********DB; pt_pin=jd********_76;", "Uid": "UID_UrcfWTF_*****YNeZe" }, { ]
> > > 应该没少吧
> > 
> > 
> > 多了,{
> 
> 正在从CK_WxPusherUid文件中检索资料... 未查询到用户的Uid,取消一对一通知发送...
> 
> 现在脚本能运行，但是跟题主一样报这个错==！

你的CK_WxPusherUid文件在哪里路径

**Comment by ROOOCCCK** [comment]
> > > > > > > ？你改jd_bean_change文件了吗
> > > > > > 
> > > > > > 
> > > > > > CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有
> > > > > 
> > > > > 
> > > > > 说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号
> > > > 
> > > > 
> > > > [ { "pt_pin": "pt_key=AAJiSlUlA__********DB; pt_pin=jd********_76;", "Uid": "UID_UrcfWTF_*****YNeZe" }, { ]
> > > > 应该没少吧
> > > 
> > > 
> > > 多了,{
> > 
> > 
> > 正在从CK_WxPusherUid文件中检索资料... 未查询到用户的Uid,取消一对一通知发送...
> > 现在脚本能运行，但是跟题主一样报这个错==！
> 
> 你的CK_WxPusherUid文件在哪里路径

/ql/data/scripts

**Comment by 6dylan6** [comment]
> > > > ？你改jd_bean_change文件了吗
> > > 
> > > 
> > > CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有
> > 
> > 
> > 说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号
> 
> [ { "pt_pin": "pt_key=AAJiSlUlA__********DB; pt_pin=jd********_76;", "Uid": "UID_UrcfWTF_*****YNeZe" }, { ]
> 
> 应该没少吧

你太6了，pt_pin不是那么甜的，参考这个模板https://github.com/6dylan6/jdpro/blob/main/config/CK_WxPusherUid.json

**Comment by ROOOCCCK** [comment]
> > > > > ？你改jd_bean_change文件了吗
> > > > 
> > > > 
> > > > CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有
> > > 
> > > 
> > > 说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号
> > 
> > 
> > [ { "pt_pin": "pt_key=AAJiSlUlA__********DB; pt_pin=jd********_76;", "Uid": "UID_UrcfWTF_*****YNeZe" }, { ]
> > 应该没少吧
> 
> 你太6了，pt_pin不是那么甜的，参考这个模板https://github.com/6dylan6/jdpro/blob/main/config/CK_WxPusherUid.json

原来是格式问题=-=，我人傻了。对了，库里面有CK检测脚本吗，就是检测有效无效那个

**Comment by 6dylan6** [comment]
> > > > > > ？你改jd_bean_change文件了吗
> > > > > 
> > > > > 
> > > > > CK_WxPusherUid.json我有手动建立这个，CKName_cache.json没有
> > > > 
> > > > 
> > > > 说错了就是CK_WxPusherUid.json这个，检查下格式可能少了括号
> > > 
> > > 
> > > [ { "pt_pin": "pt_key=AAJiSlUlA__********DB; pt_pin=jd********_76;", "Uid": "UID_UrcfWTF_*****YNeZe" }, { ]
> > > 应该没少吧
> > 
> > 
> > 你太6了，pt_pin不是那么甜的，参考这个模板https://github.com/6dylan6/jdpro/blob/main/config/CK_WxPusherUid.json
> 
> 原来是格式问题=-=，我人傻了。对了，库里面有CK检测脚本吗，就是检测有效无效那个

sendnotify有检测功能export NOTIFY_AUTOCHECKCK="true"，检测到失效自动禁用

**Comment by ROOOCCCK** [comment]
> 

要运行哪个脚本才能检测呢，在任务里面搜不到

**Comment by 6dylan6** [comment]
> > 
> 
> 要运行哪个脚本才能检测呢，在任务里面搜不到

每次发通知都会检测，你是要达到什么目的。

**Comment by ROOOCCCK** [comment]
> > > 
> > 
> > 
> > 要运行哪个脚本才能检测呢，在任务里面搜不到
> 
> 每次发通知都会检测，你是要达到什么目的。

主要是想自动禁用失效的CK，我变量设置了自动禁用但是不起作用

**Comment by 6dylan6** [comment]
> > > > 
> > > 
> > > 
> > > 要运行哪个脚本才能检测呢，在任务里面搜不到
> > 
> > 
> > 每次发通知都会检测，你是要达到什么目的。
> 
> 主要是想自动禁用失效的CK，我变量设置了自动禁用但是不起作用

不会的，检查你变量设置对不对

**Comment by ROOOCCCK** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 要运行哪个脚本才能检测呢，在任务里面搜不到
> > > 
> > > 
> > > 每次发通知都会检测，你是要达到什么目的。
> > 
> > 
> > 主要是想自动禁用失效的CK，我变量设置了自动禁用但是不起作用
> 
> 不会的，检查你变量设置对不对
![8636c7861ef6cd6dd56817432356ffb](https://user-images.githubusercontent.com/79370772/166144575-e4aedad6-63d0-403f-bb47-09821bf9006b.png)
老哥帮我看看

**Comment by 6dylan6** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 要运行哪个脚本才能检测呢，在任务里面搜不到
> > > > 
> > > > 
> > > > 每次发通知都会检测，你是要达到什么目的。
> > > 
> > > 
> > > 主要是想自动禁用失效的CK，我变量设置了自动禁用但是不起作用
> > 
> > 
> > 不会的，检查你变量设置对不对
> > ![8636c7861ef6cd6dd56817432356ffb](https://user-images.githubusercontent.com/79370772/166144575-e4aedad6-63d0-403f-bb47-09821bf9006b.png)
> > 老哥帮我看看

汗，写在config配置文件。不是环境变量

**Comment by ROOOCCCK** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 要运行哪个脚本才能检测呢，在任务里面搜不到
> > > > > 
> > > > > 
> > > > > 每次发通知都会检测，你是要达到什么目的。
> > > > 
> > > > 
> > > > 主要是想自动禁用失效的CK，我变量设置了自动禁用但是不起作用
> > > 
> > > 
> > > 不会的，检查你变量设置对不对
> > > ![8636c7861ef6cd6dd56817432356ffb](https://user-images.githubusercontent.com/79370772/166144575-e4aedad6-63d0-403f-bb47-09821bf9006b.png)
> > > 老哥帮我看看
> 
> 汗，写在config配置文件。不是环境变量

![image](https://user-images.githubusercontent.com/79370772/166150922-919122ba-9654-48c1-918f-ec8d5bfbc852.png)
zhe'y这样对吗

**Comment by 6dylan6** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 要运行哪个脚本才能检测呢，在任务里面搜不到
> > > > > > 
> > > > > > 
> > > > > > 每次发通知都会检测，你是要达到什么目的。
> > > > > 
> > > > > 
> > > > > 主要是想自动禁用失效的CK，我变量设置了自动禁用但是不起作用
> > > > 
> > > > 
> > > > 不会的，检查你变量设置对不对
> > > > ![8636c7861ef6cd6dd56817432356ffb](https://user-images.githubusercontent.com/79370772/166144575-e4aedad6-63d0-403f-bb47-09821bf9006b.png)
> > > > 老哥帮我看看
> > 
> > 
> > 汗，写在config配置文件。不是环境变量
> 
> ![image](https://user-images.githubusercontent.com/79370772/166150922-919122ba-9654-48c1-918f-ec8d5bfbc852.png) zhe'y这样对吗

export

**Comment by ROOOCCCK** [comment]
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 要运行哪个脚本才能检测呢，在任务里面搜不到
> > > > > > > 
> > > > > > > 
> > > > > > > 每次发通知都会检测，你是要达到什么目的。
> > > > > > 
> > > > > > 
> > > > > > 主要是想自动禁用失效的CK，我变量设置了自动禁用但是不起作用
> > > > > 
> > > > > 
> > > > > 不会的，检查你变量设置对不对
> > > > > ![8636c7861ef6cd6dd56817432356ffb](https://user-images.githubusercontent.com/79370772/166144575-e4aedad6-63d0-403f-bb47-09821bf9006b.png)
> > > > > 老哥帮我看看
> > > 
> > > 
> > > 汗，写在config配置文件。不是环境变量
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/79370772/166150922-919122ba-9654-48c1-918f-ec8d5bfbc852.png) zhe'y这样对吗
> 
> export

![image](https://user-images.githubusercontent.com/79370772/166205466-fb08d3aa-824b-44df-a797-5d81ff6c376e.png)
跑了一天，还是没自动禁用呀

**Comment by 6dylan6** [comment]
> > > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 要运行哪个脚本才能检测呢，在任务里面搜不到
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 每次发通知都会检测，你是要达到什么目的。
> > > > > > > 
> > > > > > > 
> > > > > > > 主要是想自动禁用失效的CK，我变量设置了自动禁用但是不起作用
> > > > > > 
> > > > > > 
> > > > > > 不会的，检查你变量设置对不对
> > > > > > ![8636c7861ef6cd6dd56817432356ffb](https://user-images.githubusercontent.com/79370772/166144575-e4aedad6-63d0-403f-bb47-09821bf9006b.png)
> > > > > > 老哥帮我看看
> > > > 
> > > > 
> > > > 汗，写在config配置文件。不是环境变量
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/79370772/166150922-919122ba-9654-48c1-918f-ec8d5bfbc852.png) zhe'y这样对吗
> > 
> > 
> > export
> 
> ![image](https://user-images.githubusercontent.com/79370772/166205466-fb08d3aa-824b-44df-a797-5d81ff6c376e.png) 跑了一天，还是没自动禁用呀
变量没有问题，sendnotify文件对不对，自动禁用会发通知，CK检查到失效

**Comment by suzhou-warreny** [comment]
请问为啥我用一键安装青龙后，没有deps这个文件夹，只有dp这个文件夹
![3ad875f499005360b5ec628944e359a](https://user-images.githubusercontent.com/86645431/175759452-820e5b6e-0995-4cc7-abdb-dd81c86200ab.png)

**Comment by suzhou-warreny** [comment]
> @suzhou-warreny你这在主机的，对的，里面看有容器，没有映射出来

怎么才能映射出来。

**Comment by sclodestar** [comment]
@6dylan6  我今晚也出错了，报错是“未查询到用户的Uid”
我确定路径，uid，都是正确的，是哪里错了？

**Comment by twguang** [comment]
> @sclodestar 全部都不行还是某个账号不行
大佬，奶酪ark在录入ck的时候可以绑定录入WxPusher的UID，怎么配置才能将UID配置到青龙实现一对一推送
