### ISSUE TITLE
东东农场: API查询请求失败 ‼️‼️ "self-signed certificate in certificate chain" function_id:farm_task_list

### ISSUE THREAD

**Issue by jy1989** [6dylan6/jdpro#150]
已更新最新代码

使用代理池运行后出现错误 

```
东东农场: API查询请求失败 ‼️‼️
"self-signed certificate in certificate chain"
function_id:farm_task_list

❗️新农场任务, 错误!

任务执行异常，请检查执行日志 ‼️‼️



❗️新农场任务, 错误!
TypeError: Cannot read properties of undefined (reading 'data')
    at _0x226d86 (/ql/data/scripts/6dylan6_jdpro/jd_fruit_new.js:10:60111)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x274482 (/ql/data/scripts/6dylan6_jdpro/jd_fruit_new.js:10:32050)
    at async /ql/data/scripts/6dylan6_jdpro/jd_fruit_new.js:10:16137
```

**Comment by jy1989** [comment]
东东农场: API查询请求失败 ‼️‼️
"self-signed certificate in certificate chain"
function_id:dongDongFarmSignHome


东东农场: API查询请求失败 ‼️‼️
"self-signed certificate in certificate chain"
function_id:farm_water



东东农场: API查询请求失败 ‼️‼️
"self-signed certificate in certificate chain"
function_id:farm_task_list

**Comment by 6dylan6** [comment]
@jy1989 你代理池配置有问题

**Comment by jy1989** [comment]
@6dylan6    感谢回复   可能是代理池里某些ip的问题
