### ISSUE TITLE
为什么自动评价报错

### ISSUE THREAD

**Issue by gaojianpete** [6dylan6/jdpro#158]
开始商品与服务评价！
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 537, in <module>
    start()
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 522, in start
    ordinary(headers, f'账号{i}[{user}]')
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 402, in ordinary
    for i, da in enumerate(op(headers)):
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 342, in op
    data = req.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>

**Comment by 6dylan6** [comment]
你这403黑ip了。换ip试试

**Comment by gaojianpete** [comment]
换ip 是 挂梯子全局是吗？

**Comment by 6dylan6** [comment]
只要能换ip就行

**Comment by gaojianpete** [comment]
好的 谢谢大佬 我去试一下

**Comment by gaojianpete** [comment]
成功是成功了 大佬 可是一个号都没评价完就又黑了

**Comment by 6dylan6** [comment]
额，没有并发跑吧

**Comment by gaojianpete** [comment]
我一直没弄明白并发跑 是我把这个任务自己复制出来几个是吗？

**Comment by 6dylan6** [comment]
那你就没并发，都黑就不知道咋回事了

**Comment by gaojianpete** [comment]
好的 我去试试并发
