### ISSUE TITLE
汪汪乐园报错了，养joy和每日任务都不能用了。

### ISSUE THREAD

**Issue by mythbobo** [6dylan6/jdpro#173]
能不能修复一下呢？

汪汪乐园养joy, 错误!
TypeError: Cannot read properties of null (reading 'level')
    at /ql/scripts/gys619_Absinthe_main/jd_joy_park_Mod.js:125:36
    at got.post.then.message (/ql/scripts/gys619_Absinthe_main/jd_joy_park_Mod.js:597:6792)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
    汪汪乐园每日任务, 开始!

====================共8个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/4/29 08:39:38=====================

******开始【京东账号1】*********

resolve start
resolve end
汪汪乐园每日任务 - 助力码: null
服务端异常，不知道为啥有时候这样，后面再观察一下，手动执行应该又没问题了

手动执行也不行

**Comment by 6dylan6** [comment]
失效了，我库里都移除了
