### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by dotaxl** [6dylan6/jdpro#174]
注册小于7天的账号，使用jd_beans_7days脚本的时候出错，应该是数组溢出，详细信息如下

Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_beans_7days.py", line 255, in <module>
    query()
  File "/ql/data/scripts/6dylan6_jdpro/jd_beans_7days.py", line 250, in query
    creat_bean_count(res['data'][3], res['data'][0], res['data'][1], res['data'][2][1:])
  File "/ql/data/scripts/6dylan6_jdpro/jd_beans_7days.py", line 159, in creat_bean_count
    tb.add_column('TOTAL', beanstotal)
  File "/usr/lib/python3.9/site-packages/prettytable/prettytable.py", line 1424, in add_column
    raise ValueError(
ValueError: Column length 0 does not match number of rows 1

@6dylan6

**Comment by 6dylan6** [comment]
有空我看下

**Comment by 6dylan6** [comment]
已修复

**Comment by dotaxl** [comment]
****** [账号7]-****   ******
未获取到数据，原因未知！！

'data'

**Comment by dotaxl** [comment]
@6dylan6 大佬新账号这样，帮忙看下是否正常

**Comment by 6dylan6** [comment]
新号等些日子吧，还没数据

**Comment by 6dylan6** [comment]
> @6dylan6 大佬新账号这样，帮忙看下是否正常

新号等几天吧， 还没有数据
