### ISSUE TITLE
wskey转换问题

### ISSUE THREAD

**Issue by chendeben** [6dylan6/jdpro#202]
249行会报错，报错原因是可能找不到retcode，我看了接口返回的数据，为：
```
{"code":"0","errMsg":"请求异常","errorCode":-100}
```

**Comment by chendeben** [comment]
```
Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_wskey.py", line 554, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "/ql/data/scripts/6dylan6_jdpro/jd_wskey.py", line 249, in check_ck
    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
KeyError: 'retcode'

## 执行结束
```

**Comment by 6dylan6** [comment]
@chendeben 好的， 每次都这样吗

**Comment by chendeben** [comment]
> @chendeben 好的， 每次都这样吗

目前我这边是必现，数下来，第6个ck就崩了，然后停了

**Comment by nono331** [comment]
Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 554, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 249, in check_ck
    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
KeyError: 'retcode'
同样的问题，也是第六个账号

**Comment by chendeben** [comment]
> Traceback (most recent call last): File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 554, in if not check_ck(jck): # bool: False 判定 JD_COOKIE 有效性 File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 249, in check_ck code = int(json.loads(res.text)['retcode']) # 使用 Json模块对返回数据取值 int([retcode]) KeyError: 'retcode' 同样的问题，也是第六个账号

目前我是设置WSKEY_UPDATE_HOUR变量以绕过这部分检测逻辑，防止报错后面不执行

**Comment by diy6188** [comment]
一样的情况，第六个账号开始崩

Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_wskey.py", line 554, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "/ql/data/scripts/6dylan6_jdpro/jd_wskey.py", line 249, in check_ck
    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
KeyError: 'retcode'

**Comment by tpc188** [comment]
现在wskey和cookie有效期都是3天，完全没有转换的必要了，直接获取cookie即可

**Comment by diy6188** [comment]
> > Traceback (most recent call last): File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 554, in if not check_ck(jck): # bool: False 判定 JD_COOKIE 有效性 File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 249, in check_ck code = int(json.loads(res.text)['retcode']) # 使用 Json模块对返回数据取值 int([retcode]) KeyError: 'retcode' 同样的问题，也是第六个账号
> 
> 目前我是设置WSKEY_UPDATE_HOUR变量以绕过这部分检测逻辑，防止报错后面不执行

能教一下怎么搞吗？找到了这行，不知道怎么改

**Comment by chendeben** [comment]
> > > Traceback (most recent call last): File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 554, in if not check_ck(jck): # bool: False 判定 JD_COOKIE 有效性 File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 249, in check_ck code = int(json.loads(res.text)['retcode']) # 使用 Json模块对返回数据取值 int([retcode]) KeyError: 'retcode' 同样的问题，也是第六个账号
> > 
> > 
> > 目前我是设置WSKEY_UPDATE_HOUR变量以绕过这部分检测逻辑，防止报错后面不执行
> 
> 能教一下怎么搞吗？找到了这行，不知道怎么改

在面板的环境变量那边新建一个变量，变量名填WSKEY_UPDATE_HOUR，值填3或者4之类的

**Comment by diy6188** [comment]
> > > > Traceback (most recent call last): File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 554, in if not check_ck(jck): # bool: False 判定 JD_COOKIE 有效性 File "/ql/data/scripts/6dylan6_jdpro_main/jd_wskey.py", line 249, in check_ck code = int(json.loads(res.text)['retcode']) # 使用 Json模块对返回数据取值 int([retcode]) KeyError: 'retcode' 同样的问题，也是第六个账号
> > > 
> > > 
> > > 目前我是设置WSKEY_UPDATE_HOUR变量以绕过这部分检测逻辑，防止报错后面不执行
> > 
> > 
> > 能教一下怎么搞吗？找到了这行，不知道怎么改
> 
> 在面板的环境变量那边新建一个变量，变量名填WSKEY_UPDATE_HOUR，值填3或者4之类的

跪谢！
