### ISSUE TITLE
如何配置多个cookie或者wskey实现多账号功能?

### ISSUE THREAD

**Issue by FairyWorld** [6dylan6/jdpro#233]

**Comment by 6dylan6** [comment]
不太明白，多个就添加环境变量

**Comment by FairyWorld** [comment]
> 不太明白，多个就添加环境变量

值是都写在同一个JD_WSCK里面，还是创建多个JD_WSCK每一个JD_WSCK对应一个值

**Comment by 6dylan6** [comment]
每行一个

**Comment by FairyWorld** [comment]
> 每行一个
我有3个号, JD_WSCK每次写入单个值时，3个号我都试过了都提示转换成功。但是如果一个JD_WSCK同时写入3个值，每行一个就会出现下面的错误。我是禁用了JD_COOKIE参数自启动JD_WSCK的情况下
![image](https://user-images.githubusercontent.com/32956212/170807351-3fa7687e-ed00-4bb5-9d23-958ea2a9f303.png)

**Comment by FairyWorld** [comment]
> 每行一个

已解决, 可能有隐藏的空格或者换行符导致格式有问题, 换成lf文本格式后粘贴一遍就行了

**Comment by 6dylan6** [comment]
ok

**Comment by liuze0109** [comment]
执行的时候，一直报这个错误，有了解的吗？

5700端口检查通过
Traceback (most recent call last):
  File "/ql/data/scripts/sign_wskey/wskey.py", line 571, in <module>
    token = ql_login()  # 调用方法 [ql_login]  并赋值 [token]
  File "/ql/data/scripts/sign_wskey/wskey.py", line 198, in ql_login
    token = auth["token"]  # 提取 authkey
KeyError: 'token'

**Comment by 6dylan6** [comment]
@liuze0109 多账号就抓ck添加就行了，你用wskey转？
