### ISSUE TITLE
东东农场 TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Michaol** [6dylan6/jdpro#241]
❗️东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'name')
    at 我尼玛_0x24bf2d (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:17:31330)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro/jd_fruit.js:17:21673

昨天还正常，今天自动同步后就挂了

**Comment by 6dylan6** [comment]
@Michaol 更新

**Comment by Michaol** [comment]
感谢大佬高速解决！
