### ISSUE TITLE
资产统计会出错

### ISSUE THREAD

**Issue by andyliang007008** [6dylan6/jdpro#262]
❗京东资产统计, 错误!
TypeError: Cannot read properties of undefined (reading 'length')
    at /ql/scripts/6dylan6_jdpro/jd_bean_change.js:2294:58
    at got.post.then.message (/ql/scripts/6dylan6_jdpro/jd_bean_change.js:2648:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by 6dylan6** [comment]
@andyliang007008 更新

**Comment by andyliang007008** [comment]
> @andyliang007008 更新

正常了，谢谢
