### ISSUE TITLE
报错Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by KillLinux** [6dylan6/jdpro#282]
手动运行依赖安装脚本基本都装不上 在面板的依赖管理中手动安装了依赖安装脚本中内容 倒是不会报缺库了 开始报这个....

**Comment by KillLinux** [comment]
`## 开始执行... 2022-06-11 15:54:33


🔔大富翁, 开始!

====================共4个京东账号Cookie=================

============脚本执行时间：2022/6/11 15:54:33=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

/ql/data/scripts/node_modules/got/dist/source/as-promise/index.js:15
const PCancelable = require("p-cancelable");
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.local/share/pnpm/global/5/.pnpm/registry.npmmirror.com+p-cancelable@4.0.0/node_modules/p-cancelable/index.js from /ql/data/scripts/node_modules/got/dist/source/as-promise/index.js not supported.
Instead change the require of /root/.local/share/pnpm/global/5/.pnpm/registry.npmmirror.com+p-cancelable@4.0.0/node_modules/p-cancelable/index.js in /ql/data/scripts/node_modules/got/dist/source/as-promise/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/ql/data/scripts/node_modules/got/dist/source/as-promise/index.js:15:21)
    at Object.<anonymous> (/ql/data/scripts/node_modules/got/dist/source/create.js:15:22)
    at Object.<anonymous> (/ql/data/scripts/node_modules/got/dist/source/index.js:14:18)
    at Object.initGotEnv (/ql/data/scripts/6dylan6_jdpro/jd_dfw_new.js:310:3742)
    at Object.post (/ql/data/scripts/6dylan6_jdpro/jd_dfw_new.js:310:5658)
    at /ql/data/scripts/6dylan6_jdpro/jd_dfw_new.js:271:5
    at new Promise (<anonymous>)
    at TotalBean (/ql/data/scripts/6dylan6_jdpro/jd_dfw_new.js:267:9)
    at /ql/data/scripts/6dylan6_jdpro/jd_dfw_new.js:30:9
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/jd_dfw_new.js:46:3) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.3.0

## 执行结束... 2022-06-11 15:54:33 耗时 0 秒`

**Comment by 6dylan6** [comment]
@KillLinux 啥版本青龙。没见过这报错。

**Comment by KillLinux** [comment]
@6dylan6 2.13.3

**Comment by KillLinux** [comment]
所有任务都报这个。。。。

**Comment by 6dylan6** [comment]
@KillLinux 我在13测试没问题，你这环境不对。重新部署试试

**Comment by KillLinux** [comment]
好的 我试试

**Comment by KillLinux** [comment]
重新部署后测试正常 感谢

**Comment by 6dylan6** [comment]
@KillLinux OK
