### ISSUE TITLE
新农场助力，旧农场助力，无法获取缓存助力码

### ISSUE THREAD

**Issue by likefu40** [6dylan6/jdpro#288]
![微信截图_20240502111631](https://github.com/6dylan6/jdpro/assets/57254076/8d581d63-4e64-426b-9ce0-116fc3fe3395)
如图新旧都无法获取缓存的互助码

![微信截图_20240502111742](https://github.com/6dylan6/jdpro/assets/57254076/e11cedc2-1620-419b-9dbf-00cc64fa5ebc)
脚本fruit_helpcode；fruit_helpcode_new中都为空，在脚本手动填写助力码后，第二天查看又被清空！

目前已在环境变量中手动添加了互助码，可正常运行

**Comment by 6dylan6** [comment]
@likefu40 你看一看农场任务正常跑完没有，跑完才写入缓存

**Comment by likefu40** [comment]
> @likefu40 你看一看农场任务正常跑完没有，跑完才写入缓存

农场7.15运行，助力7点40
新农场6.15执行   助力9点运行，  到目前fruit_helpcode；fruit_helpcode_new中都为空

**Comment by 6dylan6** [comment]
@likefu40 知道的，看任务里有没有报错，跑完没有，有没异常中断

**Comment by 6dylan6** [comment]
@6dylan6 更新修复

**Comment by xiaobuboy** [comment]
跑农场报这个错误
东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'name')
    at _0x51213b (/ql/scripts/6dylan6_jdpro/jd_fruit.js:21:28364)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/6dylan6_jdpro/jd_fruit.js:21:20486

**Comment by 6dylan6** [comment]
@xiaobuboy 日志往上面看看从哪开始报错的

**Comment by xiaobuboy** [comment]
------------------【京东账号1】jd_4d4b5******-------------------

任务执行异常，请检查执行日志 ‼️‼️



❗️东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'name')
    at _0x51213b (/ql/scripts/6dylan6_jdpro/jd_fruit.js:21:28364)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/6dylan6_jdpro/jd_fruit.js:21:20486

==============📣系统通知📣==============
东东农场-任务
【京东账号1🆔】jd_4d4b5********

**Comment by xiaobuboy** [comment]
> @xiaobuboy 日志往上面看看从哪开始报错的

------------------【京东账号1】jd_4d4b5******-------------------

任务执行异常，请检查执行日志 ‼️‼️



❗️东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'name')
    at _0x51213b (/ql/scripts/6dylan6_jdpro/jd_fruit.js:21:28364)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/6dylan6_jdpro/jd_fruit.js:21:20486

==============📣系统通知📣==============
东东农场-任务
【京东账号1🆔】jd_4d4b5********
