### ISSUE TITLE
wsck转换不了

### ISSUE THREAD

**Issue by xhbsa** [6dylan6/jdpro#289]
## 开始执行... 2022-06-16 16:48:48

--------------------

5700端口检查通过
Traceback (most recent call last):
  File "/ql/data/scripts/JDWXX_jd_job/jd_wskey.py", line 573, in <module>
    token = ql_login()  # 调用方法 [ql_login]  并赋值 [token]
  File "/ql/data/scripts/JDWXX_jd_job/jd_wskey.py", line 198, in ql_login
    token = auth["token"]  # 提取 authkey
KeyError: 'token'

## 执行结束... 2022-06-16 16:48:49 耗时 1 秒

**Comment by xhbsa** [comment]
>
