### ISSUE TITLE
jd_Evaluation.py自动评价报错

### ISSUE THREAD

**Issue by Kang128** [6dylan6/jdpro#29]
Traceback (most recent call last):
  File "/ql/scripts/6dylan6_jdpro/jd_Evaluation.py", line 523, in <module>
    start()
  File "/ql/scripts/6dylan6_jdpro/jd_Evaluation.py", line 508, in start
    ordinary(headers, f'账号{i}[{user}]')
  File "/ql/scripts/6dylan6_jdpro/jd_Evaluation.py", line 388, in ordinary
    for i, da in enumerate(op(headers)):
  File "/ql/scripts/6dylan6_jdpro/jd_Evaluation.py", line 336, in op
    data = req.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

大佬麻烦看一下

**Comment by 6dylan6** [comment]
号有问题，换个号看看

**Comment by 6dylan6** [comment]
![image](https://user-images.githubusercontent.com/86815944/154043054-1a2aa24a-7a10-41b6-9af3-61e06fdb0213.png)

**Comment by yumengbdw** [comment]
同样问题

**Comment by Youwenrui** [comment]
同样报错...

**Comment by Kang128** [comment]
换了3个号都这样

**Comment by Kang128** [comment]
> 号有问题，换个号看看

换了3个号都一样，会有可能是少了依赖吗

**Comment by gclm** [comment]
同样报错
```
开始商品与服务评价！
Traceback (most recent call last):
  File "jd_Evaluation.py", line 523, in <module>
    start()
  File "jd_Evaluation.py", line 508, in start
    ordinary(headers, f'账号{i}[{user}]')
  File "jd_Evaluation.py", line 388, in ordinary
    for i, da in enumerate(op(headers)):
  File "jd_Evaluation.py", line 336, in op
    data = req.json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by quicksandznzn** [comment]
找到原因了 换一个账号就可以了  不可以的账号会报 401 Authorization Required

**Comment by Kang128** [comment]
> 找到原因了 换一个账号就可以了 不可以的账号会报 401 Authorization Required

那就是账号的原因了，连换3个都不行😂

**Comment by Youwenrui** [comment]
请问这个怎么换账号啊，我15个ck，第一个报错了就不执行下面的了，也没看到注释哪里换账号
