### ISSUE TITLE
配置了代理，获取到ip后依然报错

### ISSUE THREAD

**Issue by flywin8** [6dylan6/jdpro#302]
容易403，建议上代理
版本：20240310
问题建议：https://t.me/dylan_jdpro
环境变量（可选项）：
export DY_PROXY='api_url' 可使用代理API
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:564:9)
    at new URL (node:internal/url:640:5)
    at new HttpsProxyAgent (/root/.local/share/pnpm/global/5/.pnpm/https-proxy-agent@7.0.4/node_modules/https-proxy-agent/dist/index.js:54:50)
    at bdy_0x319694 (/ql/data/scripts/6dylan6_jdpro_main/function/proxy.js:1:20741)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.ddd [as get] (/ql/data/scripts/6dylan6_jdpro_main/function/proxy.js:1:24609) {
  input: 'http://111.132.17.65:4247\r111.132.16.23:4230\r111.132.17.57:4253\r222.35.227.64:4253\r222.35.227.108:4253\r111.132.17.176:4230\r',
  code: 'ERR_INVALID_URL'
}

**Comment by flywin8** [comment]
每次设置提取1个既可以
