### ISSUE TITLE
轻松赚豆脚本执行第二个账号时报错

### ISSUE THREAD

**Issue by flywin8** [6dylan6/jdpro#303]
TypeError: Cannot read properties of undefined (reading 'beanShortTasks')
    at _0x56663a (/ql/data/scripts/6dylan6_jdpro_main/jd_qszd.js:6:34439)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_qszd.js:6:30311

已经开启了代理IP

**Comment by velonic5438** [comment]
我也出现这个情况 好几个都是这个代码

**Comment by 6dylan6** [comment]
@velonic5438 更新修复
