### ISSUE TITLE
推送问题

### ISSUE THREAD

**Issue by tiygu** [6dylan6/jdpro#307]
大佬，资产通知出现
日志-京东资产统计
## 开始执行... 2022-06-23 19:19:10

🔔京东资产统计, 开始!

====================共5个京东账号Cookie=================

============脚本执行时间：6/23/2022, 19:19:11=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

******开始查询【京东账号1】jd_45b2334867964*********

【账号1🆔】澨有虺
【账号信息】😊普通会员,京享值4059
【今日京豆】收83豆
【昨日京豆】收78豆
【当前京豆】794豆(≈7.94元)
【今日喜豆】收0豆
【昨日喜豆】收0豆
【当前喜豆】64喜豆(≈0.64元)
【京喜牧场】13枚鸡蛋
【极速金币】58649币(≈5.86元)
【京东赚赚】31450币(≈3.15元)
【京东秒杀】560币(≈0.56元)
【其他信息】领现金:10.84元
【东东农场】广西小米蕉3斤(70%,7天)
【京喜工厂】超能洗衣液(86%,5天)
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】0.53(总过期0.06)元 
【京喜红包】0.30(将过期0.01)元 
【极速红包】0.13(将过期0.05)元 
【京东红包】0.10(将过期0.00)元 

正在从CK_WxPusherUid文件中检索资料...
未查询到用户的Uid,取消一对一通知发送...
******开始查询【京东账号2】jd_62fd639b6274c*********
【账号2🆔】无-_-解
【账号信息】😊普通会员,京享值2654
【今日京豆】收43豆
【昨日京豆】收69豆
【当前京豆】2961豆(≈29.61元)
【今日喜豆】收0豆
【昨日喜豆】收0豆
【当前喜豆】193喜豆(≈1.93元)
【京喜牧场】245枚鸡蛋
【极速金币】92964币(≈9.30元)
【京东赚赚】47550币(≈4.75元)
【京东秒杀】500币(≈0.50元)
【其他信息】领现金:5.64元
【东东农场】新鲜橙子3斤(40%,21天)
【京喜工厂】阿宽红油面皮(93%,2天)
【东东萌宠】2只装 大号收纳袋(70%,3/4块)
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】0.29(总过期0.20)元 
【京喜红包】0.11(将过期0.02)元 
【极速红包】0.18(将过期0.18)元 

正在从CK_WxPusherUid文件中检索资料...
未查询到用户的Uid,取消一对一通知发送...
******开始查询【京东账号3】jd_iClIFoNiPJWP*********

==============📣系统通知📣==============
京东资产统计
账号3：jd_iClIFoNiPJWP
数据异常

❗️京东资产统计, 错误!
TypeError: Cannot read properties of undefined (reading 'totalWaterTaskTimes')
    at /ql/scripts/6dylan6_jdpro/jd_bean_change.js:1852:53
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/6dylan6_jdpro/jd_bean_change.js:3087:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
【账号3🆔】jd_iClIFoNiPJWP
【账号信息】😊普通会员,京享值2000
【今日京豆】收35豆,支8豆
【昨日京豆】收60豆,支9豆
【当前京豆】1541豆(≈15.41元)
【今日喜豆】收0豆
【昨日喜豆】收0豆
【当前喜豆】0喜豆(≈0.00元)
【京喜牧场】1枚鸡蛋
【极速金币】39042币(≈3.90元)
【京东赚赚】27850币(≈2.79元)
【其他信息】领现金:0.49元
💸💸💸临期京豆明细💸💸💸
【2022-06-23】过期7豆
【2022-06-24】过期26豆
【2022-06-25】过期3豆
【2022-06-26】过期3豆
【2022-06-27】过期12豆
【2022-06-28】过期5豆
【2022-06-29】过期4豆
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】0.26(总过期0.10)元 
【京喜红包】0.14(将过期0.03)元 
【极速红包】0.12(将过期0.07)元

**Comment by tiygu** [comment]
> 

ok
