### ISSUE TITLE
风扇狂转，不知道是哪个文件没找到，希望帮忙解答下

### ISSUE THREAD

**Issue by zhangbaixue** [6dylan6/jdpro#309]
Error: ??  Couldn't find .env file  ??

    at Object.<anonymous> (/ql/back/config/index.ts:35:9)

    at Module._compile (node:internal/modules/cjs/loader:1112:14)

    at Module.m._compile (/root/.local/share/pnpm/global/5/.pnpm/ts-node@10.8.1_qiyc72axg2v44xl4yovan2v55u/node_modules/ts-node/src/index.ts:1597:23)

    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)

    at Object.require.extensions.<computed> [as .ts] (/root/.local/share/pnpm/global/5/.pnpm/ts-node@10.8.1_qiyc72axg2v44xl4yovan2v55u/node_modules/ts-node/src/index.ts:1600:12)

    at Module.load (node:internal/modules/cjs/loader:988:32)

    at Function.Module._load (node:internal/modules/cjs/loader:834:12)

    at Module.require (node:internal/modules/cjs/loader:1012:19)

    at require (node:internal/modules/cjs/helpers:102:18)

    at Object.<anonymous> (/ql/back/data/index.ts:2:1)

/ql/shell/api.sh: line 157: 6dylan6_jdpro_jd_dreamFactory/2022-06-24-02-44-57.log: No such file or directory

/ql/shell/api.sh: line 157: 6dylan6_jdpro_jd_cfd/2022-06-24-02-46-28.log: No such file or directory

/ql/shell/api.sh: line 157: 6dylan6_jdpro_jd_health_collect/2022-06-24-02-49-25.log: No such file or directory

/ql/shell/api.sh: line 157: 6dylan6_jdpro_jd_health_collect/2022-06-24-02-49-25.log: No such file or directory

crond[151]: USER root pid 32091 cmd ID=166 task 6dylan6_jdpro/jd_super_redrain.js

crond[151]: USER root pid 32092 cmd ID=100 task 6dylan6_jdpro/jd_qqxing.js

/ql/back/config/index.ts:35

  throw new Error("??  Couldn't find .env file  ??");

**Comment by zhangbaixue** [comment]
用哪个青龙版本啊，给推荐个
