### ISSUE TITLE
大佬我这脚本都出现URIError: URI malformed！问题是为什么呀

### ISSUE THREAD

**Issue by Andwxa** [6dylan6/jdpro#322]
比如：
❗️京东资产统计, 错误!
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:1403:29
    at /ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:2548:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
❌ 京东资产统计, 失败! 原因: URIError: URI malformed!

❗️CK检测, 错误!
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /ql/data/scripts/6dylan6_jdpro/jd_CheckCK.js:151:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
    ❌ 新农场任务, 失败! 原因: URIError: URI malformed!

**Comment by 6dylan6** [comment]
@Andwxa 你检查ck格式

**Comment by Andwxa** [comment]
> 你检查ck格式

我的ck格式是：
pt_key=AAJmV******************9tTLn1jieDi-rsB9Lc;pt_token=6*****nb;pt_pin=jd_*****b2;
是否是这个问题

**Comment by Andwxa** [comment]
我的...CK里有中文编码很容易没了，果然哪怕账号支持中文也最好不要用中文
