### ISSUE TITLE
自动评价报错

### ISSUE THREAD

**Issue by lengchuanwen** [6dylan6/jdpro#327]
Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_Evaluation.py", line 25, in <module>
    from sendNotify import send
  File "/ql/data/scripts/6dylan6_jdpro/sendNotify.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by winsphinx** [comment]
![image](https://user-images.githubusercontent.com/5674054/180930532-ea7a6b74-ae5a-4b83-bb0b-aa99fb85d011.png)
我也报错如图。

**Comment by winsphinx** [comment]
5个号都不行
