### ISSUE TITLE
自动评价出错

### ISSUE THREAD

**Issue by q123m098** [6dylan6/jdpro#33]
## 开始执行... 2022-02-16 17:27:39

xxxxxxxxxxxx
当前环境青龙面板新版
### 开始批量评价 ###
您已配置2个账号

** 开始[账号1]-oO0___0Oo **
开始商品与服务评价！
Traceback (most recent call last):
  File "/ql/scripts/6dylan6_jdpro/jd_Evaluation.py", line 523, in <module>
    start()
  File "/ql/scripts/6dylan6_jdpro/jd_Evaluation.py", line 508, in start
    ordinary(headers, f'账号{i}[{user}]')
  File "/ql/scripts/6dylan6_jdpro/jd_Evaluation.py", line 388, in ordinary
    for i, da in enumerate(op(headers)):
  File "/ql/scripts/6dylan6_jdpro/jd_Evaluation.py", line 336, in op
    data = req.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## 执行结束... 2022-02-16 17:27:50 耗时 11 秒

**Comment by 6dylan6** [comment]
目前看是有些号跑不了，我排查一下。

**Comment by q123m098** [comment]
> 目前看是有些号跑不了，我排查一下。

感谢。。

**Comment by 6dylan6** [comment]
更新了一版，你再试试

**Comment by q123m098** [comment]
测试可以了。感谢
