### ISSUE TITLE
伊利星系牧场, 错误

### ISSUE THREAD

**Issue by cnytsoul** [6dylan6/jdpro#362]
大佬你好：

❗️伊利星系牧场, 错误!
TypeError: Cannot read properties of undefined (reading 'body')
    at Object.bdy_0x2183e2 [as getbody2] (/ql/data/scripts/6dylan6_jdpro/function/dylanx.js:1:75010)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x5d6b38 (/ql/data/scripts/6dylan6_jdpro/jd_qqxing.js:10:61015)
    at async /ql/data/scripts/6dylan6_jdpro/jd_qqxing.js:10:42620

🔔伊利星系牧场, 结束! 🕛 5.65 秒

**Comment by 6dylan6** [comment]
@cnytsoul 更新修复

**Comment by Gen0769** [comment]
怎么更新修复
