### ISSUE TITLE
❗️东东农场, 错误!

### ISSUE THREAD

**Issue by qwb04022014** [6dylan6/jdpro#376]
TypeError: Cannot read properties of undefined (reading 'code')
    at turntableFarm (/ql/scripts/6dylan6_jdpro/jd_fruit.js:536:45)
    at async doDailyTask (/ql/scripts/6dylan6_jdpro/jd_fruit.js:232:3)
    at async jdFruit (/ql/scripts/6dylan6_jdpro/jd_fruit.js:108:7)
    at async /ql/scripts/6dylan6_jdpro/jd_fruit.js:66:7
成员ID:@all企业微信应用消息发送通知消息成功🎉。

请问这个是什么问题，东东农场只有第一个账号可以正常浇水，后面的账号都报这个错误

**Comment by qwb04022014** [comment]
## 开始执行... 2022-09-04 02:28:16


🔔东东农场, 开始!
开始获取配置文件


====================共3个京东账号Cookie=================

============脚本执行时间：2022-9-4 2:28:16=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

共3个京东账号

您提供了0个账号的农场助力码

开始【京东账号1】276025797_m

由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

第1个京东账号将要助力的好友["","740aebe3c3fc4c51a878987483a0b447","cbe963cb270449f1a85fe6837175c6b6","38271ae5e71c4346893a92c336d4a265","5072d2b27aed4c688476535c43c526af","261c12bb3c064581b4e6e7d40571f151","821e7f29cac24cff9362ce2805d849e5","157157332b4b478886389f41b1805f98"]

【京东账号1（276025797_m）的东东农场好友互助码】69e3303b544c4a7fa1bad5cb4860abd7


【已成功兑换水果】3次

开始助力好友
格式化后的助力码::["","740aebe3c3fc4c51a878987483a0b447","cbe963cb270449f1a85fe6837175c6b6","38271ae5e71c4346893a92c336d4a265","5072d2b27aed4c688476535c43c526af","261c12bb3c064581b4e6e7d40571f151","821e7f29cac24cff9362ce2805d849e5","157157332b4b478886389f41b1805f98"]

开始助力京东账号1 - 276025797_m的好友: 
开始助力京东账号1 - 276025797_m的好友: 740aebe3c3fc4c51a878987483a0b447
【助力好友结果】: 好友【tyq563】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号1 - 276025797_m的好友: cbe963cb270449f1a85fe6837175c6b6
【助力好友结果】: 好友【jd_4505394c746e1】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号1 - 276025797_m的好友: 38271ae5e71c4346893a92c336d4a265
【助力好友结果】: 好友【jd_717b4ed5550c7】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号1 - 276025797_m的好友: 5072d2b27aed4c688476535c43c526af
【助力好友结果】: 好友【jd_180518pti】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号1 - 276025797_m的好友: 261c12bb3c064581b4e6e7d40571f151
【助力好友结果】: 好友【酷拉la】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号1 - 276025797_m的好友: 821e7f29cac24cff9362ce2805d849e5
【助力好友结果】: 好友【woshilimei150】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号1 - 276025797_m的好友: 157157332b4b478886389f41b1805f98
【助力好友结果】: 好友【刘来祥】已满五人助力
【今日助力次数还剩】3次

助力好友结束，即将开始领取额外水滴奖励


蜜桔3斤种植中...


初始化任务列表
开始签到
签到结果:  {"code":"2","echo":"the current API does not exist"}
被水滴砸中： 否
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

当前不在定时领水时间断或者已经领过

开始给好友浇水...

初始化任务列表
今日已给0个好友浇水
您的好友列表暂无好友,快去邀请您的好友吧!

今日已邀请好友0个 / 每日邀请上限4个
开始删除0个好友,可拿每天的邀请奖励
今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
开始打卡领水活动（签到，关注，领券）结束

水滴雨任务，每天两次，最多可得10g水滴
两次水滴雨任务是否全部完成：否
`【第2次水滴雨】未到时间，请3:44:42再试

助力好友未达到2个
领取额外奖励水滴结束

是否到了领取免费赠送的抽奖机会----false
免费赠送的抽奖机会未到时间
浏览天天抽奖的第1个逛会场任务已完成
浏览天天抽奖的第2个逛会场任务已完成
浏览天天抽奖的第3个逛会场任务已完成
浏览天天抽奖的第4个逛会场任务已完成
浏览天天抽奖的第5个逛会场任务已完成
开始天天抽奖--好友助力--每人每天只有三次助力机会.
天天抽奖-助力刘来祥成功

---天天抽奖次数remainLotteryTimes----6次
开始抽奖
等待了2秒
第1次抽奖结果{"code":"0","couponInfo":{"couponId":"346218166873","batchId":922995393,"type":1,"style":0,"beginTime":1661961600000,"endTime":1664553599000,"discount":5,"quota":10},"statisticsTimes":null,"sysTime":1662229751874,"couponResultCode":200,"message":null,"type":"coupon1","limitStr":"仅可购买惠寻等部分商品","remainLotteryTimes":5}
lotteryRes.typecoupon1
等待了2秒
第2次抽奖结果{"beanCount":1,"code":"0","statisticsTimes":null,"sysTime":1662229755017,"message":null,"type":"bean1","remainLotteryTimes":4}
lotteryRes.typebean1
等待了2秒
第3次抽奖结果{"beanCount":1,"code":"0","statisticsTimes":null,"sysTime":1662229758158,"message":null,"type":"bean1","remainLotteryTimes":3}
lotteryRes.typebean1
等待了2秒
第4次抽奖结果{"code":"0","couponInfo":{"couponId":"346218719861","batchId":923557065,"type":1,"style":0,"beginTime":1661961600000,"endTime":1664553599000,"discount":30,"quota":31},"statisticsTimes":null,"sysTime":1662229761297,"couponResultCode":200,"message":null,"type":"coupon3","limitStr":"仅可购买京东京造部分商品","remainLotteryTimes":2}
lotteryRes.typecoupon3
等待了2秒
第5次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1662229764446,"message":null,"type":"thanks","remainLotteryTimes":1}
lotteryRes.typethanks
等待了2秒
第6次抽奖结果{"beanCount":1,"code":"0","statisticsTimes":null,"sysTime":1662229767611,"message":null,"type":"bean1","remainLotteryTimes":0}
lotteryRes.typebean1
【天天抽奖】优惠券1-惠寻，京豆1个，京豆1个，优惠券3-京造，谢谢参与，京豆1个


准备浇水十次
第1次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":161,"statisticsTimes":null,"totalWaterTimes":1,"sysTime":1662229770903,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":850}
剩余水滴161g
第2次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":151,"statisticsTimes":null,"totalWaterTimes":2,"sysTime":1662229773030,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":860}
剩余水滴151g
第3次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":141,"statisticsTimes":null,"totalWaterTimes":3,"sysTime":1662229775185,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":870}
剩余水滴141g
第4次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":131,"statisticsTimes":null,"totalWaterTimes":4,"sysTime":1662229777316,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":880}
剩余水滴131g
第5次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":121,"statisticsTimes":null,"totalWaterTimes":5,"sysTime":1662229779446,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":890}
剩余水滴121g
第6次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":111,"statisticsTimes":null,"totalWaterTimes":6,"sysTime":1662229781602,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":900}
剩余水滴111g
第7次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":101,"statisticsTimes":null,"totalWaterTimes":7,"sysTime":1662229783753,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":910}
剩余水滴101g
第8次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":91,"statisticsTimes":null,"totalWaterTimes":8,"sysTime":1662229785910,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":920}
剩余水滴91g
第9次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":81,"statisticsTimes":null,"totalWaterTimes":9,"sysTime":1662229788046,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":930}
剩余水滴81g
第10次浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":71,"statisticsTimes":null,"totalWaterTimes":10,"sysTime":1662229790187,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":940}
剩余水滴71g

初始化任务列表
【首次浇水奖励】获得5g💧

【十次浇水奖励】获得10g💧

finished 水果任务完成!

初始化任务列表
暂未给2个好友浇水

小鸭子游戏:小鸭祝你新年新气象
小鸭子游戏:小鸭子为你带回了水滴
小鸭子游戏:贪吃鸭溜去采水果啦
小鸭子游戏:小鸭子和好友玩耍去啦
小鸭子游戏:小鸭子为你带回快速浇水卡
小鸭子还在努力乘风破浪
执行再次浇水
开始检查剩余水滴能否再次浇水再次浇水

剩余水滴91g

背包已有道具:
快速浇水卡:70张
水滴翻倍卡:0张
水滴换京豆卡:1张
加签卡:0张

目前剩余水滴：【91】g,不再继续浇水,保留部分水滴用于完成第二天【十次浇水得水滴】任务
开始预测水果成熟时间


初始化任务列表

==============📣系统通知📣==============
东东农场
【京东账号1🆔】276025797_m
【水果名称】蜜桔3斤
【已兑换水果】3次
【今日剩余助力👬】3次
【额外奖励】领取失败,原因：给您助力的人未达2个
【今日共浇水】10次
【剩余 水滴】91g💧
【水果进度】15.67%，已浇水94次,还需506次
【预测】50天之后(2022-10-24日)可兑换水果🍉
开始【京东账号2】小妞宝130524

由于您第2个京东账号未提供shareCode,将采纳本脚本自带的助力码

第2个京东账号将要助力的好友["","740aebe3c3fc4c51a878987483a0b447","cbe963cb270449f1a85fe6837175c6b6","38271ae5e71c4346893a92c336d4a265","5072d2b27aed4c688476535c43c526af","261c12bb3c064581b4e6e7d40571f151","821e7f29cac24cff9362ce2805d849e5","157157332b4b478886389f41b1805f98"]

【京东账号2（jd_520d845d62783）的东东农场好友互助码】2f74bb24aa8440a993be27627fb3185a


【已成功兑换水果】3次

开始助力好友
格式化后的助力码::["","740aebe3c3fc4c51a878987483a0b447","cbe963cb270449f1a85fe6837175c6b6","38271ae5e71c4346893a92c336d4a265","5072d2b27aed4c688476535c43c526af","261c12bb3c064581b4e6e7d40571f151","821e7f29cac24cff9362ce2805d849e5","157157332b4b478886389f41b1805f98"]

开始助力京东账号2 - 小妞宝130524的好友: 
开始助力京东账号2 - 小妞宝130524的好友: 740aebe3c3fc4c51a878987483a0b447
【助力好友结果】: 好友【tyq563】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号2 - 小妞宝130524的好友: cbe963cb270449f1a85fe6837175c6b6
【助力好友结果】: 好友【jd_4505394c746e1】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号2 - 小妞宝130524的好友: 38271ae5e71c4346893a92c336d4a265
【助力好友结果】: 好友【jd_717b4ed5550c7】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号2 - 小妞宝130524的好友: 5072d2b27aed4c688476535c43c526af
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
开始助力京东账号2 - 小妞宝130524的好友: 261c12bb3c064581b4e6e7d40571f151
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
开始助力京东账号2 - 小妞宝130524的好友: 821e7f29cac24cff9362ce2805d849e5
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
开始助力京东账号2 - 小妞宝130524的好友: 157157332b4b478886389f41b1805f98
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
助力好友结束，即将开始领取额外水滴奖励


十万个为什么+中华上下五千年种植中...


初始化任务列表
开始签到
签到结果:  {"code":"2","echo":"the current API does not exist"}
被水滴砸中： 否
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

当前不在定时领水时间断或者已经领过

开始给好友浇水...

初始化任务列表
今日已给0个好友浇水
您的好友列表暂无好友,快去邀请您的好友吧!

今日已邀请好友0个 / 每日邀请上限4个
开始删除0个好友,可拿每天的邀请奖励
今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
开始打卡领水活动（签到，关注，领券）结束

水滴雨任务，每天两次，最多可得10g水滴
两次水滴雨任务是否全部完成：否
`【第2次水滴雨】未到时间，请3:46:01再试

助力好友未达到2个
领取额外奖励水滴结束

是否到了领取免费赠送的抽奖机会----false
免费赠送的抽奖机会未到时间
浏览天天抽奖的第1个逛会场任务已完成
浏览天天抽奖的第2个逛会场任务已完成
浏览天天抽奖的第3个逛会场任务已完成
浏览天天抽奖的第4个逛会场任务已完成
浏览天天抽奖的第5个逛会场任务已完成
开始天天抽奖--好友助力--每人每天只有三次助力机会.
任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read properties of undefined (reading 'code')
    at turntableFarm (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:536:45)
    at async doDailyTask (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:232:3)
    at async jdFruit (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:108:7)
    at async /ql/data/scripts/6dylan6_jdpro/jd_fruit.js:66:7

==============📣系统通知📣==============
东东农场
京东账号2 小妞宝130524
任务执行异常，请检查执行日志 ‼️‼️

==============📣系统通知📣==============
东东农场
【京东账号2🆔】小妞宝130524
【水果名称】十万个为什么+中华上下五千年
【已兑换水果】3次
【今日剩余助力👬】3次
【额外奖励】领取失败,原因：给您助力的人未达2个

开始【京东账号3】卿文文恰饭了

由于您第3个京东账号未提供shareCode,将采纳本脚本自带的助力码

第3个京东账号将要助力的好友["","740aebe3c3fc4c51a878987483a0b447","cbe963cb270449f1a85fe6837175c6b6","38271ae5e71c4346893a92c336d4a265","5072d2b27aed4c688476535c43c526af","261c12bb3c064581b4e6e7d40571f151","821e7f29cac24cff9362ce2805d849e5","157157332b4b478886389f41b1805f98"]

【京东账号3（jd_426d3dbb600ae）的东东农场好友互助码】763da4b355b5471aa9364ad8e4abafc8


【已成功兑换水果】4次

开始助力好友
格式化后的助力码::["","740aebe3c3fc4c51a878987483a0b447","cbe963cb270449f1a85fe6837175c6b6","38271ae5e71c4346893a92c336d4a265","5072d2b27aed4c688476535c43c526af","261c12bb3c064581b4e6e7d40571f151","821e7f29cac24cff9362ce2805d849e5","157157332b4b478886389f41b1805f98"]

开始助力京东账号3 - 卿文文恰饭了的好友: 
开始助力京东账号3 - 卿文文恰饭了的好友: 740aebe3c3fc4c51a878987483a0b447
【助力好友结果】: 好友【tyq563】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号3 - 卿文文恰饭了的好友: cbe963cb270449f1a85fe6837175c6b6
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
开始助力京东账号3 - 卿文文恰饭了的好友: 38271ae5e71c4346893a92c336d4a265
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
开始助力京东账号3 - 卿文文恰饭了的好友: 5072d2b27aed4c688476535c43c526af
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
开始助力京东账号3 - 卿文文恰饭了的好友: 261c12bb3c064581b4e6e7d40571f151
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
开始助力京东账号3 - 卿文文恰饭了的好友: 821e7f29cac24cff9362ce2805d849e5
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
开始助力京东账号3 - 卿文文恰饭了的好友: 157157332b4b478886389f41b1805f98
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
助力好友结束，即将开始领取额外水滴奖励


可爱创意手机支架种植中...


初始化任务列表
开始签到
签到结果:  {"code":"2","echo":"the current API does not exist"}
被水滴砸中： 否
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

当前不在定时领水时间断或者已经领过

开始给好友浇水...

初始化任务列表
今日已给0个好友浇水
您的好友列表暂无好友,快去邀请您的好友吧!

今日已邀请好友0个 / 每日邀请上限4个
开始删除0个好友,可拿每天的邀请奖励
今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
开始打卡领水活动（签到，关注，领券）结束

水滴雨任务，每天两次，最多可得10g水滴
两次水滴雨任务是否全部完成：否
`【第2次水滴雨】未到时间，请3:42:25再试

助力好友未达到2个
领取额外奖励水滴结束

是否到了领取免费赠送的抽奖机会----false
免费赠送的抽奖机会未到时间
浏览天天抽奖的第1个逛会场任务已完成
浏览天天抽奖的第2个逛会场任务已完成
浏览天天抽奖的第3个逛会场任务已完成
浏览天天抽奖的第4个逛会场任务已完成
浏览天天抽奖的第5个逛会场任务已完成
开始天天抽奖--好友助力--每人每天只有三次助力机会.
任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read properties of undefined (reading 'code')
    at turntableFarm (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:536:45)
    at async doDailyTask (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:232:3)
    at async jdFruit (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:108:7)
    at async /ql/data/scripts/6dylan6_jdpro/jd_fruit.js:66:7

==============📣系统通知📣==============
东东农场
京东账号3 卿文文恰饭了
任务执行异常，请检查执行日志 ‼️‼️

==============📣系统通知📣==============
东东农场
【京东账号3🆔】卿文文恰饭了
【水果名称】可爱创意手机支架
【已兑换水果】4次
【今日剩余助力👬】3次
【额外奖励】领取失败,原因：给您助力的人未达2个


🔔东东农场, 结束! 🕛 172.909 秒


## 执行结束... 2022-09-04 02:31:09 耗时 173 秒

**Comment by qwb04022014** [comment]
账号顺序切换了几次，发现只要是第一个的，就不会报错
