### ISSUE TITLE
京喜工厂错误

### ISSUE THREAD

**Issue by 0xFF336699** [6dylan6/jdpro#384]
❗️京喜工厂, 错误!
TypeError: Cannot read properties of undefined (reading 'assistListToday')
    at /ql/scripts/6dylan6_jdpro/jd_dreamFactory.js:519:23
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/6dylan6_jdpro/jd_dreamFactory.js:1699:4869)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

**Comment by 0xFF336699** [comment]
> @0xFF336699 坏了。这个活动没必要玩了。啥也没有

谢谢
