### ISSUE TITLE
你好，东东农场又出错了。。。

### ISSUE THREAD

**Issue by wolfhnhn** [6dylan6/jdpro#387]
第一个账号最后还能正常显示统计信息，水果有多少天能种好什么的，后边的都不行了，比较多的出错信息。
## 开始执行... 2022-09-14 11:10:35

🔔东东农场, 开始!
开始获取配置文件

====================共5个京东账号Cookie=================

============脚本执行时间：2022/9/14 11:10:35=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

共5个京东账号

您提供了5个账号的农场助力码

开始【京东账号1】----------

第1个京东账号将要助力的好友["----------","----------","----------","----------","----------","----------","----------","----------","----------","----------","----------"]

【京东账号1（----------）的东东农场好友互助码】----------

【已成功兑换水果】15次

开始助力好友
开始助力京东账号1 - ----------的好友: ----------
【助力好友结果】: 助力【----------】失败，您今天助力次数已耗尽
【今日助力次数还剩】0次

您当前助力次数已耗尽，跳出助力
助力好友结束，即将开始领取额外水滴奖励

沙棘汁4瓶种植中...

初始化任务列表
被水滴砸中： 是
【被水滴砸中】获得5g💧\n
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

【定时领水】获得8g💧

开始给好友浇水...

初始化任务列表
今日已给0个好友浇水
您的好友列表暂无好友,快去邀请您的好友吧!

今日已邀请好友0个 / 每日邀请上限4个
开始删除0个好友,可拿每天的邀请奖励
接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
开始打卡领水活动（签到，关注，领券）结束

水滴雨任务，每天两次，最多可得10g水滴
两次水滴雨任务是否全部完成：否
开始水滴雨任务,这是第2次，剩余0次
水滴雨waterRain
水滴雨任务执行成功，获得水滴：10g
【第2次水滴雨】获得10g水滴

已成功领取第01阶段好友助力奖励：【40】g水
已成功领取第11阶段好友助力奖励：【40】g水

京东昵称【----------】 在 2022-9-14 6:13:13 给您助过力

京东昵称【----------】 在 2022-9-14 6:15:15 给您助过力

京东昵称【----------】 在 2022-9-14 6:16:16 给您助过力

京东昵称【----------】 在 2022-9-14 6:18:18 给您助过力

领取额外奖励水滴结束

是否到了领取免费赠送的抽奖机会----true
领取定时奖励结果{"code":"0","addTimes":1,"statisticsTimes":null,"sysTime":1663125085329,"message":null,"remainLotteryTimes":1}
浏览天天抽奖的第1个逛会场任务已完成
浏览天天抽奖的第2个逛会场任务已完成
浏览天天抽奖的第3个逛会场任务已完成
浏览天天抽奖的第4个逛会场任务已完成
浏览天天抽奖的第5个逛会场任务已完成
浏览天天抽奖的第6个逛会场任务已完成
开始浏览天天抽奖的第7个逛会场任务
浏览爆品会场
第7个逛会场任务完成，开始领取水滴奖励

天天抽奖浏览任务领取水滴
第7个逛会场任务领取水滴奖励完成

浏览天天抽奖的第8个逛会场任务已完成
开始天天抽奖--好友助力--每人每天只有三次助力机会.
天天抽奖-不要重复助力----------

天天抽奖-不要重复助力----------

天天抽奖-不要重复助力----------

天天抽奖-助力----------失败,助力次数耗尽

---天天抽奖次数remainLotteryTimes----2次
开始抽奖
等待了2秒
第1次抽奖结果{"beanCount":1,"code":"0","statisticsTimes":null,"sysTime":1663125102554,"message":null,"type":"bean1","remainLotteryTimes":1}
lotteryRes.typebean1
等待了2秒
第2次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1663125105866,"message":null,"type":"thanks","remainLotteryTimes":0}
lotteryRes.typethanks
【天天抽奖】京豆1个，谢谢参与

今日已完成10次浇水任务

初始化任务列表
首次浇水奖励已领取

finished 水果任务完成!

初始化任务列表
暂未给2个好友浇水

小鸭子游戏达到上限
执行再次浇水
开始检查剩余水滴能否再次浇水再次浇水

剩余水滴203g

背包已有道具:
快速浇水卡:444张
水滴翻倍卡:0张
水滴换京豆卡:1张
加签卡:0张

目前剩余水滴：【203】g，可继续浇水
等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":193,"statisticsTimes":null,"totalWaterTimes":38,"sysTime":1663125113641,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2490}

浇水10g成功,剩余193

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":183,"statisticsTimes":null,"totalWaterTimes":39,"sysTime":1663125115862,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2500}

浇水10g成功,剩余183

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":173,"statisticsTimes":null,"totalWaterTimes":40,"sysTime":1663125118014,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2510}

浇水10g成功,剩余173

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":163,"statisticsTimes":null,"totalWaterTimes":41,"sysTime":1663125120153,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2520}

浇水10g成功,剩余163

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":153,"statisticsTimes":null,"totalWaterTimes":42,"sysTime":1663125122304,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2530}

浇水10g成功,剩余153

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":143,"statisticsTimes":null,"totalWaterTimes":43,"sysTime":1663125124443,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2540}

浇水10g成功,剩余143

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":133,"statisticsTimes":null,"totalWaterTimes":44,"sysTime":1663125126730,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2550}

浇水10g成功,剩余133

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":123,"statisticsTimes":null,"totalWaterTimes":45,"sysTime":1663125128928,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2560}

浇水10g成功,剩余123

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":113,"statisticsTimes":null,"totalWaterTimes":46,"sysTime":1663125131381,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2570}

浇水10g成功,剩余113

等待了1秒
本次浇水结果:   {"code":"0","totalEnergy":103,"statisticsTimes":null,"totalWaterTimes":47,"sysTime":1663125133638,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2580}

浇水10g成功,剩余103

开始预测水果成熟时间

初始化任务列表

==============📣系统通知📣==============
东东农场
【京东账号1🆔】----------
【水果名称】沙棘汁4瓶
【已兑换水果】15次
【今日剩余助力👬】0次
【额外奖励】80g水领取成功
【助力您的好友】----------,----------,----------,----------
【今日共浇水】47次
【剩余 水滴】103g💧
【水果进度】43.00%，已浇水258次,还需342次
【预测】8天之后(2022-09-22日)可兑换水果🍉
开始【京东账号2】----------

第2个京东账号将要助力的好友["----------","----------","----------","----------","----------","----------","----------","----------","----------","----------","----------"]

【京东账号2（----------）的东东农场好友互助码】----------

【已成功兑换水果】4次

开始助力好友
开始助力京东账号2 - ----------的好友: ----------
【助力好友结果】: 之前给【----------】助力过了
【今日助力次数还剩】2次

开始助力京东账号2 - ----------的好友: ----------
【助力好友结果】: 已成功给【----------】助力
给好友【----------】助力获得1g水滴
【今日助力次数还剩】1次

开始助力京东账号2 - ----------的好友: ----------
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
【助力好友👬】获得1g💧

助力好友结束，即将开始领取额外水滴奖励

柠檬3斤种植中...

初始化任务列表
被水滴砸中： 是
【被水滴砸中】获得5g💧\n
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

【定时领水】获得4g💧

开始给好友浇水...

初始化任务列表
今日已给1个好友浇水
需要浇水的好友列表shareCodes:[]
【好友浇水】已给0个好友浇水,消耗0g水

今日已邀请好友0个 / 每日邀请上限4个
开始删除1个好友,可拿每天的邀请奖励

开始删除好友 [----------]
删除好友 [----------] 成功

今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
开始打卡领水活动（签到，关注，领券）结束

水滴雨任务，每天两次，最多可得10g水滴
两次水滴雨任务是否全部完成：否
开始水滴雨任务,这是第2次，剩余0次
水滴雨waterRain
水滴雨任务执行成功，获得水滴：10g
【第2次水滴雨】获得10g水滴

已成功领取第01阶段好友助力奖励：【40】g水

京东昵称【----------】 在 2022-9-14 6:9:9 给您助过力

京东昵称【----------】 在 2022-9-14 6:15:15 给您助过力

京东昵称【----------】 在 2022-9-14 6:18:18 给您助过力

领取额外奖励水滴结束

是否到了领取免费赠送的抽奖机会----true
领取定时奖励结果{"code":"0","addTimes":1,"statisticsTimes":null,"sysTime":1663125174377,"message":null,"remainLotteryTimes":1}
浏览天天抽奖的第1个逛会场任务已完成
浏览天天抽奖的第2个逛会场任务已完成
浏览天天抽奖的第3个逛会场任务已完成
浏览天天抽奖的第4个逛会场任务已完成
浏览天天抽奖的第5个逛会场任务已完成
浏览天天抽奖的第6个逛会场任务已完成
开始浏览天天抽奖的第7个逛会场任务
浏览爆品会场
第7个逛会场任务完成，开始领取水滴奖励

天天抽奖浏览任务领取水滴
第7个逛会场任务领取水滴奖励完成

浏览天天抽奖的第8个逛会场任务已完成
开始天天抽奖--好友助力--每人每天只有三次助力机会.
---天天抽奖次数remainLotteryTimes----2次
开始抽奖
等待了2秒
第1次抽奖结果{"beanCount":1,"code":"0","statisticsTimes":null,"sysTime":1663125184957,"message":null,"type":"bean1","remainLotteryTimes":1}
lotteryRes.typebean1
等待了2秒
第2次抽奖结果{"beanCount":1,"code":"0","statisticsTimes":null,"sysTime":1663125188158,"message":null,"type":"bean1","remainLotteryTimes":0}
lotteryRes.typebean1
【天天抽奖】京豆1个，京豆1个

今日已完成10次浇水任务

初始化任务列表
首次浇水奖励已领取

finished 水果任务完成!

初始化任务列表
暂未给2个好友浇水

小鸭子游戏达到上限
执行再次浇水
开始检查剩余水滴能否再次浇水再次浇水

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read properties of undefined (reading 'totalEnergy')
    at doTenWaterAgain (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:343:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async jdFruit (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:116:9)
    at async /ql/data/scripts/6dylan6_jdpro/jd_fruit.js:66:7

==============📣系统通知📣==============
东东农场
【京东账号2🆔】----------
【水果名称】柠檬3斤
【已兑换水果】4次
【今日剩余助力👬】1次
【额外奖励】40g水领取成功
【助力您的好友】----------,----------,----------

开始【京东账号3】----------

第3个京东账号将要助力的好友["----------","----------","----------","----------","----------","----------","----------","----------","----------","----------","----------"]

【京东账号3（----------）的东东农场好友互助码】----------

【已成功兑换水果】2次

开始助力好友
开始助力京东账号3 - ----------的好友: ----------
【助力好友结果】: 之前给【----------】助力过了
【今日助力次数还剩】1次

开始助力京东账号3 - ----------的好友: ----------
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
助力好友结束，即将开始领取额外水滴奖励

==============📣系统通知📣==============
东东农场
【京东账号3】----------
【提醒⏰】流油海鸭蛋6枚已可领取
请去京东APP或微信小程序查看
点击弹窗即达
开始【京东账号4】----------

第4个京东账号将要助力的好友["----------","----------","----------","----------","----------","----------","----------","----------","----------","----------","----------"]

【京东账号4（jd_4efe166db94f8）的东东农场好友互助码】----------

【已成功兑换水果】1次

开始助力好友
开始助力京东账号4 - ----------的好友: ----------
【助力好友结果】: 之前给【----------】助力过了
【今日助力次数还剩】2次

开始助力京东账号4 - ----------的好友: ----------
【助力好友结果】: 已成功给【----------】助力
给好友【----------】助力获得1g水滴
【今日助力次数还剩】1次

开始助力京东账号4 - ----------的好友: ----------
【助力好友结果】: 已成功给【----------】助力
给好友【----------】助力获得1g水滴
【今日助力次数还剩】0次

您当前助力次数已耗尽，跳出助力
【助力好友👬】获得2g💧

助力好友结束，即将开始领取额外水滴奖励

柠檬3斤种植中...

初始化任务列表
被水滴砸中： 是
【被水滴砸中】获得5g💧\n
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

【定时领水】获得6g💧

开始给好友浇水...

初始化任务列表
今日已给1个好友浇水
需要浇水的好友列表shareCodes:[]
【好友浇水】已给0个好友浇水,消耗0g水

今日已邀请好友0个 / 每日邀请上限4个
开始删除1个好友,可拿每天的邀请奖励

开始删除好友 [----------]
删除好友 [----------] 成功

今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
开始打卡领水活动（签到，关注，领券）结束

水滴雨任务，每天两次，最多可得10g水滴
两次水滴雨任务是否全部完成：否
开始水滴雨任务,这是第2次，剩余0次
水滴雨waterRain
水滴雨任务执行成功，获得水滴：10g
【第2次水滴雨】获得10g水滴

助力好友未达到2个

京东昵称【----------】 在 2022-9-14 6:9:9 给您助过力

领取额外奖励水滴结束

是否到了领取免费赠送的抽奖机会----true
领取定时奖励结果{"code":"0","addTimes":1,"statisticsTimes":null,"sysTime":1663125236377,"message":null,"remainLotteryTimes":1}
浏览天天抽奖的第1个逛会场任务已完成
浏览天天抽奖的第2个逛会场任务已完成
浏览天天抽奖的第3个逛会场任务已完成
浏览天天抽奖的第4个逛会场任务已完成
浏览天天抽奖的第5个逛会场任务已完成
浏览天天抽奖的第6个逛会场任务已完成
开始浏览天天抽奖的第7个逛会场任务
浏览爆品会场
第7个逛会场任务完成，开始领取水滴奖励

天天抽奖浏览任务领取水滴
第7个逛会场任务领取水滴奖励完成

浏览天天抽奖的第8个逛会场任务已完成
开始天天抽奖--好友助力--每人每天只有三次助力机会.
---天天抽奖次数remainLotteryTimes----2次
开始抽奖
等待了2秒
第1次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1663125246980,"message":null,"type":"thanks","remainLotteryTimes":1}
lotteryRes.typethanks
等待了2秒
第2次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1663125250277,"message":null,"type":"thanks","remainLotteryTimes":0}
lotteryRes.typethanks
【天天抽奖】谢谢参与，谢谢参与

今日已完成10次浇水任务

初始化任务列表
首次浇水奖励已领取

finished 水果任务完成!

初始化任务列表
暂未给2个好友浇水

小鸭子游戏达到上限
执行再次浇水
开始检查剩余水滴能否再次浇水再次浇水

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read properties of undefined (reading 'totalEnergy')
    at doTenWaterAgain (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:343:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async jdFruit (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:116:9)
    at async /ql/data/scripts/6dylan6_jdpro/jd_fruit.js:66:7

==============📣系统通知📣==============
东东农场
【京东账号4🆔】----------
【水果名称】柠檬3斤
【已兑换水果】1次
【今日剩余助力👬】0次
【额外奖励】领取失败,原因：给您助力的人未达2个
【助力您的好友】----------

开始【京东账号5】----------

第5个京东账号将要助力的好友["----------","----------","----------","----------","----------","----------","----------","----------","----------","----------","----------"]

【京东账号5（----------）的东东农场好友互助码】----------

【已成功兑换水果】8次

开始助力好友
开始助力京东账号5 - ----------的好友: ----------
【助力好友结果】: 助力【----------】失败，您今天助力次数已耗尽
【今日助力次数还剩】0次

您当前助力次数已耗尽，跳出助力
助力好友结束，即将开始领取额外水滴奖励

12枚徐香猕猴种植中...

初始化任务列表
被水滴砸中： 是
【被水滴砸中】获得5g💧\n
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

【定时领水】获得6g💧

给2个好友浇水任务已完成

今日已邀请好友0个 / 每日邀请上限4个
开始删除1个好友,可拿每天的邀请奖励

开始删除好友 [----------]
删除好友 [----------] 成功

今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
开始打卡领水活动（签到，关注，领券）结束

水滴雨任务，每天两次，最多可得10g水滴
两次水滴雨任务是否全部完成：否
开始水滴雨任务,这是第2次，剩余0次
水滴雨waterRain
水滴雨任务执行成功，获得水滴：10g
【第2次水滴雨】获得10g水滴

助力好友未达到2个
领取额外奖励水滴结束

是否到了领取免费赠送的抽奖机会----true
领取定时奖励结果{"code":"0","addTimes":1,"statisticsTimes":null,"sysTime":1663125293882,"message":null,"remainLotteryTimes":1}
浏览天天抽奖的第1个逛会场任务已完成
浏览天天抽奖的第2个逛会场任务已完成
浏览天天抽奖的第3个逛会场任务已完成
浏览天天抽奖的第4个逛会场任务已完成
浏览天天抽奖的第5个逛会场任务已完成
浏览天天抽奖的第6个逛会场任务已完成
开始浏览天天抽奖的第7个逛会场任务
浏览爆品会场
第7个逛会场任务完成，开始领取水滴奖励

天天抽奖浏览任务领取水滴
第7个逛会场任务领取水滴奖励完成

浏览天天抽奖的第8个逛会场任务已完成
开始天天抽奖--好友助力--每人每天只有三次助力机会.
---天天抽奖次数remainLotteryTimes----2次
开始抽奖
等待了2秒
第1次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1663125309250,"message":null,"type":"thanks","remainLotteryTimes":1}
lotteryRes.typethanks
等待了2秒
第2次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1663125313502,"message":null,"type":"thanks","remainLotteryTimes":0}
lotteryRes.typethanks
【天天抽奖】谢谢参与，谢谢参与

今日已完成10次浇水任务

初始化任务列表
首次浇水奖励已领取

finished 水果任务完成!

初始化任务列表
给好友浇水的25g水滴奖励已领取

小鸭子游戏达到上限
执行再次浇水
开始检查剩余水滴能否再次浇水再次浇水

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read properties of undefined (reading 'totalEnergy')
    at doTenWaterAgain (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:343:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async jdFruit (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:116:9)
    at async /ql/data/scripts/6dylan6_jdpro/jd_fruit.js:66:7

==============📣系统通知📣==============
东东农场
【京东账号5🆔】----------
【水果名称】12枚徐香猕猴
【已兑换水果】8次
【今日剩余助力👬】0次
【额外奖励】领取失败,原因：给您助力的人未达2个

🔔东东农场, 结束! 🕛 286.557 秒

## 执行结束... 2022-09-14 11:15:21 耗时 286 秒

**Comment by caidesen** [comment]
{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}
是不是调用过快导致的

**Comment by wolfhnhn** [comment]
> {"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"} 是不是调用过快导致的

不知道。。。有哪个参数能调整账号间的时间间隔？

**Comment by wolfhnhn** [comment]
> {"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"} 是不是调用过快导致的

昨天还没问题了。。。
