### ISSUE TITLE
拉库通知脚本问题

### ISSUE THREAD

**Issue by Burden-xy** [6dylan6/jdpro#406]
每次拉库的时候6dylan6_jdpro下的sendNotify.js就会被覆盖成老版本的，好像会导致NOTIFY_SKIP_LIST参数不起作用
青龙是2.11.3版本的。拉库地址用的是https://js.dayplus.xyz/https://github.com/6dylan6/jdpro.git

/*
 * @Author: lxk0301 https://gitee.com/lxk0301
 * @Date: 2020-08-19 16:12:40
 * @Last Modified by: whyour
 * @Last Modified time: 2021-5-1 15:00:54
 * sendNotify 推送通知功能
 * @param text 通知头
 * @param desp 通知体
 * @param params 某些推送通知方式点击弹窗可跳转, 例：{ url: 'https://abc.com' }
 * @param author 作者仓库等信息  例：`本通知 By：https://github.com/whyour/qinglong`
 */

**Comment by Burden-xy** [comment]
替换容器里的JS以后拉库确实不会被覆盖了，但是NOTIFY_SKIP_LIST参数好像依然不生效，已经在环境变量和config.sh里都设置了
config.sh   export NOTIFY_SKIP_LIST="惊喜工厂&东东农场”

[root@PC 6dylan6_jdpro]# cat sendNotify.js |grep NOTIFY_SKIP_LIST
        const notifySkipList = process.env.NOTIFY_SKIP_LIST ? process.env.NOTIFY_SKIP_LIST.split('&') : [];

**Comment by Burden-xy** [comment]
这个应该是没错的 QAQ
## 其他需要的变量，脚本中需要的变量使用 export 变量名= 声明即可
export DY_OPENALL="true"
export PET_NOTIFY_CONTROL="true"
export FRUIT_NOTIFY_CONTROL="true"
export JOY_FEED_COUNT="80"
export exjxbeans="true"
export Ev_Start="true"
export DY_ZJD="true"
export JD_CART_REMOVE="true"
export JD_TRY="true"
#export FRUIT_NOTIFY_CONTROL="false"
#export PET_NOTIFY_CONTROL="false"
export NOTIFY_SKIP_LIST="惊喜工厂&东东农场"
export PandaToken='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODg

**Comment by Burden-xy** [comment]
【京东账号3（XXXX）的京喜工厂好友互助码】XXXX
已投入电力：3100000
所需电力：3100000
生产进度：100.00%


商品兑换已超时

❗️京喜工厂, 错误!
TypeError: Cannot read properties of undefined (reading 'assistListToday')
    at /ql/scripts/6dylan6_jdpro/jd_dreamFactory.js:519:23
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/6dylan6_jdpro/jd_dreamFactory.js:1699:4869)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
开始
第3个京东账号将要助力的好友["ZZZ",""]
助力朋友：ZZZ成功，因一次只能助力一个，故跳出助力

❗️京喜工厂, 错误!
TypeError: Cannot read properties of undefined (reading 'currentElectricityQuantity')
    at /ql/scripts/6dylan6_jdpro/jd_dreamFactory.js:347:47
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/6dylan6_jdpro/jd_dreamFactory.js:1699:4869)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
完成任务：共领取0电力
投入失败，生产失效了，请稍后重试~

  商品名     兑换状态
束口便当袋    兑换超时

【京东账号3】ZZZZ
【生产商品】束口便当袋
【当前等级】研究员 8
【生产进度】100.00%
【每日任务】领奖成功，共计 0 电力
【投入电力】投入失败，生产失效了，请稍后重试~
【收取自己零件】今日已达上限
【收取好友零件】今日已达上限

开始发送通知...
通知标题: 京喜工厂
成员ID:@all企业微信应用消息发送通知消息成功🎉。


🔔京喜工厂, 结束! 🕛 13.096 秒


## 执行结束... 2022-10-07 21:42:32 耗时 22 秒
