### ISSUE TITLE
京喜财富岛

### ISSUE THREAD

**Issue by 161123** [6dylan6/jdpro#426]
## 开始执行... 2022-10-20 18:51:55

🔔京喜财富岛, 开始!

====================共1个京东账号Cookie=================

============脚本执行时间：2022/10/20 18:51:56=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

获取签名参数成功！

******开始【京东账号1】xxxxxxxxx**************

获取用户信息：success

当前等级:undefined,金币:undefined,财富值:undefined,连续营业天数:undefined,离线收益:undefined

❗️京喜财富岛, 错误!
TypeError: Cannot read properties of undefined (reading 'TaskList')
    at /ql/scripts/6dylan6_jdpro/jd_cfd.js:1409:51
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/6dylan6_jdpro/jd_cfd.js:2116:4871)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
寻宝

❗️京喜财富岛, 错误!
TypeError: Cannot read properties of undefined (reading 'filter')
    at cfd (/ql/scripts/6dylan6_jdpro/jd_cfd.js:148:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/6dylan6_jdpro/jd_cfd.js:89:9
助力升级中。。。

🔔京喜财富岛, 结束! 🕛 4.585 秒

## 执行结束... 2022-10-20 18:52:00 耗时 5 秒

**Comment by 161123** [comment]
> @161123 云服务器？

对腾讯云

**Comment by 161123** [comment]
> @161123 ip被风控了，换本地吧
额，我下午刚买的服务器，本地就是拿自己电脑搞么

**Comment by 161123** [comment]
> @161123 本地电脑或服务器都行啊

他又正常了。。。
