### ISSUE TITLE
资产推送每次运行前都会报错

### ISSUE THREAD

**Issue by mizhihan** [6dylan6/jdpro#437]
![20221023_211529](https://user-images.githubusercontent.com/71163533/197395391-3d954304-45f3-42f1-b585-381cff26be94.jpg)
dan但是推送到手机上的没有报错的文字，强迫症想知道这是为什么

**Comment by mizhihan** [comment]
>

**Comment by mizhihan** [comment]
> @mizhihan 更新

不是的，我是才拉的您库。不知道是不是和deps有关，我后来把sendnotify放进了drps里重新拉仍然是这样。但是错误代码下面是可以正常显示出账号的信息的。并不影响使用，只是看着不太美观。

**Comment by mizhihan** [comment]
> @mizhihan 更新
还有就是经过我多次尝试发现库依赖那里填不填sendnotify似乎都会拉取deps里面的文件那么依赖那里填写sendnotify的意义是什么呢

**Comment by mizhihan** [comment]
> @mizhihan 是的，deps下是青龙默认的，可以替换成库里的，不然每次都会被覆盖

我分别试了一次deps替换和不替换，但都会报错

**Comment by mizhihan** [comment]
> @mizhihan 更新了吗，有更新

更新了
![Screenshot_20221024_093426](https://user-images.githubusercontent.com/71163533/197430724-bb1a7d0a-6659-4f87-8372-d01ffe2c3341.jpg)
不知道是不是这个的原因

**Comment by kissgaby** [comment]
京东资产统计, 错误!
TypeError: Cannot read properties of undefined (reading 'wished')
    at /ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:2957:56
    at got.post.then.message (/ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:3452:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

一样的错误,只是我没有强迫症.哈哈,一真用到现在,不影响使用和发送通知WXpusher.
青龙版本2.14.3

**Comment by mizhihan** [comment]
> @mizhihan 是什么报错

就是他说不能理解wished,但是报错后不影响
![20221023_211529](https://user-images.githubusercontent.com/71163533/197431044-a6de25e0-48f3-4850-8c5a-6476273f9611.jpg)
正常运行

**Comment by mizhihan** [comment]
现在正常了，我青龙里设置的自动更新更新失败了。现在手动更新了一次就可以了。

**Comment by kissgaby** [comment]
> @kissgaby 那你还没更新啊。昨天我把这个停了都，不可能在报这个拉

OK,谢谢大佬
