### ISSUE TITLE
【错误】京东魔方红包雨脚本运行报错

### ISSUE THREAD

**Issue by MagicCheshireMeow** [6dylan6/jdpro#448]
错误提示：TypeError: Cannot read properties of undefined (reading '3')
    at /ql/data/scripts/6dylan6_jdpro_main/jd_mfredrain.js:71:60
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/6dylan6_jdpro_main/jd_mfredrain.js:172:5721)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

青龙版本：v2.14.8

**Comment by MagicCheshireMeow** [comment]
现在正常了
