### ISSUE TITLE
带图评价 sharp版本为0.32.5

### ISSUE THREAD

**Issue by BecherYes** [6dylan6/jdpro#452]
♻️当前使用内置sign，控制变量SIGN_URL

老青龙版本，sharp依赖请安装0.32.6之前版本

当前版本：20240822 fix
每次运行最多20个账号(变量EVALNUM调整)，每个账号最多评价10个商品
差评关键词变量 EVAL_CPKEY='xxx&yyy' 多个&连接
问题反馈：https://t.me/dylan_jdpro

屏蔽差评内容关键词：["垃圾","质量差","差评","好差","欺骗"]

******开始【京东账号1】*********

TypeError: _0x130ea4[_0x553931] is not a function
    at _0x24520b (/ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:100476)
    at _0x546cc6 (/ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:95248)
    at Object.wzaNV (/ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:53541)
    at _0x5e5716 (/ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:57370)
    at Object.GYxbm (/ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:42531)
    at /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:51309
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

等待5秒...

**Comment by shaufo** [comment]
去依赖管理，添加  sharp  即可
![image](https://github.com/user-attachments/assets/d237d39d-8f79-4172-87e1-91e4f4fcc806)

**Comment by z2ctian** [comment]
> 去依赖管理，添加 sharp 即可 ![image](https://private-user-images.githubusercontent.com/63514384/363507779-d237d39d-8f79-4172-87e1-91e4f4fcc806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDI2MTQsIm5iZiI6MTcyNTUwMjMxNCwicGF0aCI6Ii82MzUxNDM4NC8zNjM1MDc3NzktZDIzN2QzOWQtOGY3OS00MTcyLTg3ZTEtOTFlNGY0ZmNjODA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDAyMTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NjNmYTI5ZDVhOTUwOTUyMWQ3YmU4NWY0MjY4YmUzNWVjZTRhOTVlYjY5Y2QwMjJhMjc3YjI0MzU4MThiYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.euv6IGUd5MVRhROSM2tlhHdEqjm-orh5ONhQ_HLyoS4)

sharp依赖安装失败
![Uploading 1725502519860.png…]()

**Comment by BecherYes** [comment]
> 去依赖管理，添加 sharp 即可 ![image](https://private-user-images.githubusercontent.com/63514384/363507779-d237d39d-8f79-4172-87e1-91e4f4fcc806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTMyODksIm5iZiI6MTcyNTUxMjk4OSwicGF0aCI6Ii82MzUxNDM4NC8zNjM1MDc3NzktZDIzN2QzOWQtOGY3OS00MTcyLTg3ZTEtOTFlNGY0ZmNjODA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA1MDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMGVjMTBhMDhjOTM1YTkyMGI0MWQxNTdhNDY5YTZlMGQyMzMyNzBiMjMyODc0NjcwNWViOTk3MjliZTc0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-GzQy8NxIiOZeWKpd9-vaDnjX-FVhJS6Gjd-csue9OI)

sharp已安装，但还是报错，和上面的一样
![Snipaste_2024-09-05_13-09-45](https://github.com/user-attachments/assets/9e32bdd9-190a-4ab1-b99f-382120135cd0)

**Comment by u-mie** [comment]
我也显示这个，换新版本青龙安装最新sharp也不行

**Comment by fomodj** [comment]
sharp@0.32.5安装不上

**Comment by cy465728759** [comment]
解决了吗，一样的报错

**Comment by BecherYes** [comment]
> 解决了吗，一样的报错

解决了，更新下库就好了

**Comment by z2ctian** [comment]
> 解决了吗，一样的报错

青龙版本2.13，下载的sharp@32，解决了
