### ISSUE TITLE
金融捕鱼助力-第二个账号开始报错

### ISSUE THREAD

**Issue by Sarmay** [6dylan6/jdpro#460]
问题一：三个账号，只出来前两个助力码，第三个没打印

问题二：设置FISH_CODE两个助力码后运行，第二个账号开始报错

当前版本：202408023

TypeError: _0x3d7148[_0x50ecd1(...)] is not a function
    at _0x448ed0 (/ql/data/scripts/6dylan6_jdpro_main/jd_fish_help.js:6:49803)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_fish_help.js:6:41562
    
    
<img width="785" alt="image" src="https://github.com/user-attachments/assets/ba8b8c1d-6f53-4c7c-8137-b151e5f4ecde">

**Comment by z2ctian** [comment]
金融捕鱼怎么拉的，我怎么没有
