### ISSUE TITLE
go-cqhttp通知API调用失败

### ISSUE THREAD

**Issue by duzidada** [6dylan6/jdpro#464]
Go-cqhttp 通知调用API失败😞
 MaxRedirectsError: Redirected 10 times. Aborting.
    at Request._onResponseBase (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:859:35)
    at Request._onResponse (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/ql/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at Socket.socketOnData (node:_http_client:540:22)
    at Socket.emit (node:events:519:28) {
  code: 'ERR_TOO_MANY_REDIRECTS',
  timings: undefined
}

麻烦请问是哪里出错了，其他库通知是正常的

**Comment by 6dylan6** [comment]
@duzidada 你换个使用正常的sendNotify文件

**Comment by duzidada** [comment]
> @duzidada 你换个使用正常的sendNotify文件

麻烦问一下，是替换库里的吗？

**Comment by 6dylan6** [comment]
@duzidada 你用哪个库的正常就用哪个，放到deps下，不然被青龙自带的覆盖
