### ISSUE TITLE
晒图评价问题

### ISSUE THREAD

**Issue by amudream** [6dylan6/jdpro#471]
开始获取商品好评和图片...
Client network socket disconnected before secure TLS connection was established
获取商品评价信息失败！！！
该商品无图片资源！
没有获取到评价和图片,使用内置文字评价，去发布✍️✍️✍️...

Client network socket disconnected before secure TLS connection was established
TypeError: Cannot read properties of undefined (reading 'message')
    at /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:114403
    at /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:7:6903
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
评价内容(56字) ：非常满意的购物体验！商品质量很好，价格实惠。物流迅速，包装严密。非常感谢商家的耐心解答和及时发货，给予8分好评。

去评价 👉 百事可乐 Pepsi 碳酸饮料 330ml*6听 整箱 (新老包装随机发货) 百事出品(295945559125)

开始获取商品好评和图片...
Client network socket disconnected before secure TLS connection was established
获取商品评价信息失败！！！
该商品无图片资源！
没有获取到评价和图片,使用内置文字评价，去发布✍️✍️✍️...

Client network socket disconnected before secure TLS connection was established
TypeError: Cannot read properties of undefined (reading 'message')
    at /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:114403
    at /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:7:6903
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
评价内容(62字) ：这是一次愉快的购物体验，商品质量非常好，价格也很实惠。物流速度快，包装严密。非常感谢商家的耐心服务和及时回复，给予8分好评。

去评价 👉 维达（Vinda）超韧手帕纸4层7张*12包 与凤行联名款 纸巾小包 面巾纸(299980302217)

开始获取商品好评和图片...
Client network socket disconnected before secure TLS connection was established
获取商品评价信息失败！！！
该商品无图片资源！
没有获取到评价和图片,使用内置文字评价，去发布✍️✍️✍️...

Client network socket disconnected before secure TLS connection was established
TypeError: Cannot read properties of undefined (reading 'message')
    at /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:114403
    at /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:7:6903
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
评价内容(51字) ：商品收到了，非常满意！质量可以，价格也还合理。感谢商家客服的热情服务和及时发货，好的话会推荐给朋友们。

去评价 👉 通用(2961011111137)
评价完成可获得 30 豆 🥔，评价官有机会翻倍
Client network socket disconnected before secure TLS connection was established
TypeError: Cannot read properties of undefined (reading 'commentFloorList')
    at _0x1e83f9 (/ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:103498)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x308237 (/ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:72556)
    at async /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:55811

等待5秒...

**Comment by 6dylan6** [comment]
@amudream 检查运行网络吧，没这问题
