### ISSUE TITLE
农场第三个账号之后统计都报这个错

### ISSUE THREAD

**Issue by yinguohui** [6dylan6/jdpro#472]
TypeError: Cannot read properties of undefined (reading 'totalWaterTaskTimes')
    at /ql/scripts/6dylan6_jdpro/jd_bean_change.js:2035:53
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/6dylan6_jdpro/jd_bean_change.js:3400:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by yinguohui** [comment]
这是账号的问题还是什么问题呢？
