### ISSUE TITLE
晒图评价问题Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by BecherYes** [6dylan6/jdpro#474]
开始查找评价物流服务（有豆的）...

当前有24个待评价晒单，开始评价最后一页的4个商品...

去评价 👉 立白洗衣粉大师香氛洁清新除菌去渍洗衣粉手洗机洗深层去渍不伤手 大师香氛洗衣粉35g*1袋(299868196416)

开始获取商品好评和图片...
Response code 403 (Forbidden)
TypeError: Cannot read properties of undefined (reading 'commentInfo')
    at _0x3e1b59 (/ql/data/scripts/6dylan6_jdpro_main/jd_AutoEval.js:6:68481)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_AutoEval.js:6:51935

等待5秒...

🔔带图评价晒单, 结束! 🕛 12.62 秒

**Comment by BecherYes** [comment]
0913最新版本

**Comment by BecherYes** [comment]
好像是现在锁IP了，同个IP不能评价很多，大概十几条就被403了，重连网络就又可以了

**Comment by 616145694-qq** [comment]
我也是

去评价 👉 好奇（Huggies） 【返8元券】小森林试用装尿不湿心钻装拉拉裤大码L4片(9-14kg)(303353717385)

开始获取商品好评和图片...
Response code 403 (Forbidden)
获取商品评价信息失败！！！
