### ISSUE TITLE
特价版签到提现新-部分账号会出错

### ISSUE THREAD

**Issue by charleschangz** [6dylan6/jdpro#479]
错误情况：

去做任务...
TypeError: Cannot read properties of undefined (reading '0')
    at _0x22fcb2 (/ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:44503)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:36194

**Comment by charleschangz** [comment]
这个错误又出来了。
******开始【京东账号3】xxx*********

当前签到金：0.65

今日以签过!

去做任务...
TypeError: Cannot read properties of undefined (reading '0')
    at _0x22fcb2 (/ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:44503)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:36194
