### ISSUE TITLE
jd_joy_feedPets.js 日志溢出

### ISSUE THREAD

**Issue by wsz987** [6dylan6/jdpro#494]
位置 `log\6dylan6_jdpro_jd_joy_feedPets`
![image](https://user-images.githubusercontent.com/51685914/202832457-81c86cf7-ed2d-4a3b-b3c3-44824a67d806.png)

`❗️宠汪汪🐕喂食, 错误!

*****开始【京东账号1】******

JDJR验证中......
evalmachine.<anonymous>:1
<script>top.self.location.href='http://*.*.*.*/eportal/index.jsp?wlanuserip=49534987642bf08c158c6b4b42ebef75&wlanacname=83319f692649fc811f98c2c67c6cacd9&ssid=&nasip=25d7e6e74e215016bd7ed35de8772882&snmpagentip=&mac=d36108ff29ed2cd5ccf3cf3c45430e84&t=wireless-v2&url=8bdc5d129a6749beed50166cb467a132e85ea106b2004b3b52c1492d0cce9ca81c3f5acbb9fe727ff2d3da3c9927d3a8924eaf83b6509a5fb82f33fbb6dea39ad001d0d8e60368ef9eb2a2c760d0094b36155e5eed4b5779c4f2b9ed8fea82035deb5ade474d5039714ba185378b30fc36fe340a9cc4c7b0d3d84953c769d305&apmac=&nasid=83319f692649fc811f98c2c67c6cacd9&vid=0b6aa86511fd6249&port=bbd009ed1ba7bad8&nasportid=5b9da5b08a53a5406074e387142893f71ac248c7f2cee23ee170e649c4fd9077'</script>
^

SyntaxError: Unexpected token '<'
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInContext (node:vm:288:10)
    at IncomingMessage.<anonymous> (/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js:345:16)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
evalmachine.<anonymous>:1
<script>top.self.location.href='http://*.*.*.*/eportal/index.jsp?wlanuserip=49534987642bf08c158c6b4b42ebef75&wlanacname=83319f692649fc811f98c2c67c6cacd9&ssid=&nasip=25d7e6e74e215016bd7ed35de8772882&snmpagentip=&mac=d36108ff29ed2cd5ccf3cf3c45430e84&t=wireless-v2&url=8bdc5d129a6749beed50166cb467a132e85ea106b2004b3b52c1492d0cce9ca81c3f5acbb9fe727ff2d3da3c9927d3a8924eaf83b6509a5fb82f33fbb6dea39ad001d0d8e60368ef9eb2a2c760d0094b36155e5eed4b5779c4f2b9ed8fea820333cf487f6d10df1f1aa26e612bca8cb2f25d81f1daf009d0f5906f3dcb757ab0&apmac=&nasid=83319f692649fc811f98c2c67c6cacd9&vid=0b6aa86511fd6249&port=bbd009ed1ba7bad8&nasportid=5b9da5b08a53a5406074e387142893f71ac248c7f2cee23ee170e649c4fd9077'</script>
^

SyntaxError: Unexpected token '<'
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInContext (node:vm:288:10)
    at IncomingMessage.<anonymous> (/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js:345:16)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
evalmachine.<anonymous>:1
<script>top.self.location.href='http://*.*.*.*/eportal/index.jsp?wlanuserip=49534987642bf08c158c6b4b42ebef75&wlanacname=83319f692649fc811f98c2c67c6cacd9&ssid=&nasip=25d7e6e74e215016bd7ed35de8772882&snmpagentip=&mac=d36108ff29ed2cd5ccf3cf3c45430e84&t=wireless-v2&url=8bdc5d129a6749beed50166cb467a132e85ea106b2004b3b52c1492d0cce9ca81c3f5acbb9fe727ff2d3da3c9927d3a8924eaf83b6509a5fb82f33fbb6dea39ad001d0d8e60368ef9eb2a2c760d0094b36155e5eed4b5779c4f2b9ed8fea82033c4e3dfc79488112acd3901cfe3e2d480098168a1c8b2718dfcd90ca5f9a3637&apmac=&nasid=83319f692649fc811f98c2c67c6cacd9&vid=0b6aa86511fd6249&port=bbd009ed1ba7bad8&nasportid=5b9da5b08a53a5406074e387142893f71ac248c7f2cee23ee170e649c4fd9077'</script>
^`

**Comment by wsz987** [comment]
> @wsz987 服务器还是软路由

软路由 宿舍断网后循环请求，应该是没做重连次数限制
