### ISSUE TITLE
极速版汪汪赛跑

### ISSUE THREAD

**Issue by Toylee2019** [6dylan6/jdpro#506]
## 开始执行... 2022-11-27 13:11:18
**# 正在应用 优先Cookie 模式...
# 当前总共 12 个有效账号，其中前 11 个账号为固定顺序。
# 本次从第 12 个账号开始按随机顺序参加活动。
====================共12个京东账号Cookie=================

============脚本执行时间：2022-11-27 13:11:23=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

共12个京东账号**

每周日18点组队分红！！

开始【京东账号1】toylee

当前公网IP: 112.101.102.50
今日成功 0 次
今日收益 0.00 元
Error TypeError: Cannot read properties of undefined (reading 'members')
    at /ql/data/scripts/6dylan6_jdpro/jd_joy_joy_run.ts:49:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

开始【京东账号2】jd_515307cd74d23

今日成功 0 次
今日收益 0.00 元
Error TypeError: Cannot read properties of undefined (reading 'members')
    at /ql/data/scripts/6dylan6_jdpro/jd_joy_joy_run.ts:49:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Toylee2019** [comment]
当前公网IP是怎么来的 小区NAT的地址？？？

**Comment by Toylee2019** [comment]
把本地docker重新装了  青龙版本v2.15.1
还是不行
开始【京东账号1】toylee

今日成功 0 次
今日收益 0.00 元
Error TypeError: Cannot read properties of undefined (reading 'members')
    at /ql/data/scripts/6dylan6_jdpro/jd_joy_joy_run.ts:49:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

开始【京东账号2】jd_515307cd74d23

今日成功 0 次
今日收益 0.00 元
Error TypeError: Cannot read properties of undefined (reading 'members')
    at /ql/data/scripts/6dylan6_jdpro/jd_joy_joy_run.ts:49:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


是所有号都黑了？

**Comment by Toylee2019** [comment]
@6dylan6 太可了我有时间 用什么远程 我联系你

**Comment by hitjob** [comment]
解决了么？我也是一样的问题

**Comment by Toylee2019** [comment]
> 解决了么？我也是一样的问题

我安装的依赖有问题 大佬给我重新修复了 
不过我最后重新部署了青龙 用库的任务安装的依赖 就好了

**Comment by q1351884885** [comment]
怎么用库安装依赖，可以指教一下吗？

**Comment by hitjob** [comment]
> > 解决了么？我也是一样的问题
> 
> 我安装的依赖有问题 大佬给我重新修复了 不过我最后重新部署了青龙 用库的任务安装的依赖 就好了

具体涉及到哪个依赖啊？不想都重新装

**Comment by q1351884885** [comment]
> > > 解决了么？我也是一样的问题
> > 
> > 
> > 我安装的依赖有问题 大佬给我重新修复了 不过我最后重新部署了青龙 用库的任务安装的依赖 就好了
> 
> 具体涉及到哪个依赖啊？不想都重新装

不清楚，还不在家，等回家了重新部署

**Comment by q1351884885** [comment]
@6dylan6 不会啊 老哥 用的面板里面的一键安装

**Comment by hitjob** [comment]
> @hitjob axios安装0.27.2版本

多谢大佬！搞定了
之前都是手动安装的依赖，全部删除掉，用库里的依赖安装两遍，日志中发现缺少typescript，手动安装后所有脚本都正常了，非常感谢！
