### ISSUE TITLE
got.extend is not a function

### ISSUE THREAD

**Issue by rickychaw** [6dylan6/jdpro#509]
老大，奇怪的问题。。。这是怎么回事？重新拉库了，还是不行。。

`===========脚本执行时间：2024/10/07 13:38:00============
>>>>>>>>>>>>6dylan6提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

/ql/data/scripts/6dylan6_jdpro/sendNotify.js:2135
const api = got.extend({
                ^

TypeError: got.extend is not a function
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/sendNotify.js:2135:17)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/jd_joypark_task.js:6:17775)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

Node.js v20.17.0`

**Comment by 6dylan6** [comment]
@rickychaw 你运行依赖安装任务试试

**Comment by dick86114** [comment]
我也遇到了，所有程序都报这个异常，一开始是提示got模组不存在，拉依赖不会安装got，手动安装后又提示这个错误

**Comment by gemini-hub** [comment]
同样的问题，有解决方案吗？

/ql/data/scripts/6dylan6_jdpro_main/sendNotify.js:2130
const api = got.extend({
                ^

TypeError: got.extend is not a function
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro_main/sendNotify.js:2130:17)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro_main/jd_CheckCK.js:6:29)

**Comment by 6dylan6** [comment]
@gemini-hub 装最新got依赖，,或者青龙用老版本，2.19版本有这问题

**Comment by gemini-hub** [comment]
2.17版本确实没有这个问题

**Comment by dick86114** [comment]
> 同样的问题，有解决方案吗？
> 
> /ql/data/scripts/6dylan6_jdpro_main/sendNotify.js:2130 const api = got.extend({ ^
> 
> TypeError: got.extend is not a function at Object. (/ql/data/scripts/6dylan6_jdpro_main/sendNotify.js:2130:17) at Module._compile (node:internal/modules/cjs/loader:1562:14) at Object..js (node:internal/modules/cjs/loader:1699:10) at Module.load (node:internal/modules/cjs/loader:1313:32) at Function._load (node:internal/modules/cjs/loader:1123:12) at TracingChannel.traceSync (node:diagnostics_channel:322:14) at wrapModuleLoad (node:internal/modules/cjs/loader:217:24) at Module.require (node:internal/modules/cjs/loader:1335:12) at require (node:internal/modules/helpers:136:16) at Object. (/ql/data/scripts/6dylan6_jdpro_main/jd_CheckCK.js:6:29)

安装旧版got可解决，got@11.8.5

**Comment by psonys** [comment]
> > 同样的问题，有解决方案吗？
> > /ql/data/scripts/6dylan6_jdpro_main/sendNotify.js:2130 const api = got.extend({ ^
> > TypeError：got.extend 不是 Object 的函数。 （/ql/data/scripts/6dylan6_jdpro_main/sendNotify.js:2130:17）位于 Module._compile 处（node：internal/modules/cjs/loader：1562：14）位于 Object..js 处（node：internal/modules/cjs/loader：1699：10）位于 Module.load 处（node：internal/modules/cjs/loader：1313：32）位于 Function._load 处（node：internal/modules/cjs/loader：1123：12）位于 TracingChannel.traceSync 处（node：diagnostics_channel：322：14）位于 wrapModuleLoad 处（node：internal/modules/cjs/loader：217：24）位于 Module.require 处（node：internal/modules/cjs/loader：1335：12）位于 require 处（node：internal/modules/helpers：136：16）在对象处。（/ql/data/scripts/6dylan6_jdpro_main/jd_CheckCK.js:6:29）
> 
> 安装旧版本已可解决，got@11.8.5

已解决，装了指定版本好了
