### ISSUE TITLE
特价签到部分账号不行

### ISSUE THREAD

**Issue by charleschangz** [6dylan6/jdpro#518]
******开始【京东账号5】1*********

当前签到金：2.53

今日以签过!

去做任务...
TypeError: Cannot read properties of undefined (reading '0')
    at _0x22fcb2 (/ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:44503)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:36194

6个号，4个不行，2个可以

**Comment by 6dylan6** [comment]
@charleschangz 更新试试

**Comment by charleschangz** [comment]
部分可以了，6个号，2个不行，4个可以
错误还是之前的
