### ISSUE TITLE
种豆得豆，种豆得豆内部互助脚本报错

### ISSUE THREAD

**Issue by 2604237845** [6dylan6/jdpro#52]
## 开始执行... 2023-07-17 17:22:00

# 优先固定账号数量不得大于或等于有效账号总量，本次暂不重组 Cookie ...

🔔种豆得豆, 开始!
/usr/local/bin/ds:2
# -*- coding: utf-8 -*-
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro_main/function/cache/index.js:1:9455)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.16.1

## 开始执行... 2023-07-17 15:33:01

# 优先固定账号数量不得大于或等于有效账号总量，本次暂不重组 Cookie ...

🔔种豆得豆内部互助, 开始!
/usr/local/bin/ds:2
# -*- coding: utf-8 -*-
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro_main/function/cache/index.js:1:9455)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.16.1

## 执行结束...   耗时 4 秒

**Comment by 6dylan6** [comment]
@2604237845 都怎么装的青龙呀，能把ds装进python依赖，去删掉就好

**Comment by 2604237845** [comment]
> @2604237845 都怎么装的青龙呀，能把ds装进python依赖，去删掉就好

大佬牛皮…我是傻逼😵‍💫

**Comment by ghsssss** [comment]
大佬牛逼
