### ISSUE TITLE
特价版签到提现新报错

### ISSUE THREAD

**Issue by Sarmay** [6dylan6/jdpro#529]
🔔特价版签到提现新, 开始!

====================共3个京东账号Cookie=================
===========脚本执行时间：2024/10/15 10:30:20============
>>>>>>>>>>>>6dylan6提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

---------------已配置1个API接口（非白名单）代理已开启---------------

当前版本：20241012
问题建议：https://t.me/dylan_jdpro

******开始【京东账号1】*********

使用代理IP：119.7.136.9:3828
当前签到金：4.27

今日以签过!

去做任务...
TypeError: Cannot read properties of undefined (reading 'length')
    at hIHLRy (/ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:41367)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:37387

******开始【京东账号2】*********

当前签到金：4.42

去签到...
获得 0.01 签到金 💰️
获得 0.10 红包 🧧

去做任务...
TypeError: Cannot read properties of undefined (reading 'length')
    at hIHLRy (/ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:41367)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_tjqd_new.js:6:37387

<img width="996" alt="image" src="https://github.com/user-attachments/assets/1cd3413a-aeec-4ab6-9dd7-d9ff9af1b8bd">

**Comment by 6dylan6** [comment]
@Sarmay 你进app看看有任务可做吗

**Comment by Sarmay** [comment]
没有看，但是不应该报错吧

**Comment by 6dylan6** [comment]
@Sarmay 因为目前没收到其他人没反馈，我这也正常，感觉你环境问题

**Comment by Sarmay** [comment]
@6dylan6 昨天新装的docker环境，新拉去的任务列表，已经执行依赖安装了，全部执行了一遍，然后挨个看了一下有没有报错。就发现这些问题了

**Comment by Toylee2019** [comment]
同问
