### ISSUE TITLE
汪汪庄园合成报错

### ISSUE THREAD

**Issue by Sarmay** [6dylan6/jdpro#530]
当前版本：20240928
跑几次可能会黑，一周后解除
问题建议：https://t.me/dylan_jdpro

******开始【京东账号1】*********

等级:22|金币:5.36兆

===== JOY 状态 start =====
在逛街的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
id:615239|name: 航海汪|level: 20
id:615240|name: 旅行汪|level: 18

在铲土的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
工位: 1 [已开]|JOY= id:615217|name: 运动汪|level: 22
工位: 2 [已开]|JOY= id:615232|name: 叮当汪|level: 21
工位: 3 [未开]|JOY= 空位
工位: 4 [未开]|JOY= 空位
工位: 5 [未开]|JOY= 空位
===== JOY 状态  end  =====

❗️汪汪庄园合成, 错误!
TypeError: Cannot read properties of undefined (reading 'filter')
    at /ql/data/scripts/6dylan6_jdpro_main/jd_wwmanor_merge.js:8:48798
    at got.post.then.message (/ql/data/scripts/6dylan6_jdpro_main/jd_wwmanor_merge.js:9:6688)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
从工位移除 => id:615217|name: 运动汪|level: 22
从工位移除 => id:615232|name: 叮当汪|level: 21
工位清理完成！
没有可合成的JOY开始买买买🛒🛒🛒
最高能买18级的JOY，剩余5.36兆金币
购买18级JOY 成功！

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/8fca6eb3-b024-4e31-8db5-c9c6d594b54a">

**Comment by 6dylan6** [comment]
@Sarmay 你反馈的这几个我都正常，更确信你那边问题了，什么机器，云服务吗，时间对不对

**Comment by Sarmay** [comment]
家里的nas；昨天装的飞牛云OS；打印的执行时间来看，时间是正确的。X86机器，处理器N5105

**Comment by 6dylan6** [comment]
@Sarmay 网络呢，走代理？有什么拦截吗

**Comment by Sarmay** [comment]
电信千兆宽带，没有任何拦截，携趣的代理。网络中没有其他代理。

**Comment by Sarmay** [comment]
@6dylan6 大牌1010也在报错

<img width="996" alt="image" src="https://github.com/user-attachments/assets/6b74c900-1fb3-4ab3-b5a4-660587be839b">

**Comment by Sarmay** [comment]
金融捕鱼助理，第二个账号开始报错

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/a26628f3-1ba7-499a-bb7d-fa9c9da4f7ae">

**Comment by Sarmay** [comment]
宠汪汪-双人赛，第二个账号开始报错

<img width="998" alt="image" src="https://github.com/user-attachments/assets/991162d6-7733-46a9-924e-f13a5594a070">
