### ISSUE TITLE
带图评价报错

### ISSUE THREAD

**Issue by cy465728759** [6dylan6/jdpro#540]
脚本：jd_AutoEval.js

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

当前版本：20241010 
每次运行最多20个账号(可变量EVALNUM调整)，每个账号最多评价10个商品
差评关键词变量 EVAL_CPKEY='xxx&yyy' 多个&连接
问题反馈：https://t.me/dylan_jdpro

屏蔽差评内容关键词：["垃圾","质量差","差评","好差","欺骗"]

******开始【京东账号1】chen465*********

TypeError: J7Jqyz0[AVtZq1] is not a function
    at cohjseJ (/ql/scripts/6dylan6_jdpro/jd_AutoEval.js:6:90499)
    at Hf4S4a (/ql/scripts/6dylan6_jdpro/jd_AutoEval.js:6:88103)
    at hkIF6Pu (/ql/scripts/6dylan6_jdpro/jd_AutoEval.js:6:52067)
    at /ql/scripts/6dylan6_jdpro/jd_AutoEval.js:6:50639
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
等待5秒...

依赖是sharp@0.32.0；[v2.11.3]

这要怎么解决

**Comment by 6dylan6** [comment]
重新执行还是这样吗

**Comment by cy465728759** [comment]
还是不行， 换成sharp@0.32.5 也同样报错

**Comment by cy465728759** [comment]
还是不行， 换成sharp@0.32.5 也同样报错

**Comment by cy465728759** [comment]
> 重新执行还是这样吗

还是不行， 换成sharp@0.32.5 也同样报错
