### ISSUE TITLE
评价运行会报错

### ISSUE THREAD

**Issue by cyxnzb** [6dylan6/jdpro#554]
20号的版本还是会报错

开始获取商品好评和图片...
调整图片中...
RequestError
    at ClientRequest.<anonymous> (/ql/data/scripts/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/ql/data/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1117:18)
    at internalConnectMultiple (node:net:1185:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1711:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1729588239075,
    socket: 1729588239075,
    lookup: 1729588239077,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1729588239329,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 2,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 254
    }
  }
}

**Comment by 6dylan6** [comment]
@cyxnzb 你环境或依赖问题了

**Comment by cyxnzb** [comment]
> @cyxnzb 你环境或依赖问题了

我看看，先谢谢啦

**Comment by cyxnzb** [comment]
> @cyxnzb 你环境或依赖问题了

sharp这个库依赖装不上，高版本用不了，低版本不行

**Comment by cyxnzb** [comment]
> @cyxnzb 你环境或依赖问题了

sharp库装上了，但是还是有问题
RequestError
    at ClientRequest.<anonymous> (/ql/data/scripts/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/ql/data/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1117:18)
    at internalConnectMultiple (node:net:1185:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1711:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1729597261964,
    socket: 1729597261974,
    lookup: 1729597261977,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1729597262234,
    abort: undefined,
    phases: {
      wait: 10,
      dns: 3,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 270
    }
  }
}

**Comment by xiaopang-8** [comment]
我这边评价经常403

开始获取商品好评和图片...
Response code 403 (Forbidden)
获取商品评价信息失败！！！


开始评价物流服务（有豆的）...
Response code 403 (Forbidden)
Response code 403 (Forbidden)
Response code 403 (Forbidden)
Response code 403 (Forbidden)
Response code 403 (Forbidden)
Response code 403 (Forbidden)
Response code 403 (Forbidden)

**Comment by cyxnzb** [comment]
> 我这边评价经常403
> 
> 开始获取商品好评和图片... Response code 403 (Forbidden) 获取商品评价信息失败！！！
> 
> 开始评价物流服务（有豆的）... Response code 403 (Forbidden) Response code 403 (Forbidden) Response code 403 (Forbidden) Response code 403 (Forbidden) Response code 403 (Forbidden) Response code 403 (Forbidden) Response code 403 (Forbidden)

403没救了

**Comment by derek926** [comment]
同样问题，请问你是怎么安装上sharp的？

> > @cyxnzb 你环境或依赖问题了
> 
> sharp库装上了，但是还是有问题 RequestError at ClientRequest. (/ql/data/scripts/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:111) at Object.onceWrapper (node:events:634:26) at ClientRequest.emit (node:events:531:35) at origin.emit (/ql/data/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20) at TLSSocket.socketErrorListener (node:_http_client:500:9) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: at internalConnectMultiple (node:net:1117:18) at internalConnectMultiple (node:net:1185:5) at Timeout.internalConnectMultipleTimeout (node:net:1711:5) at listOnTimeout (node:internal/timers:575:11) at process.processTimers (node:internal/timers:514:7) { code: 'ETIMEDOUT', timings: { start: 1729597261964, socket: 1729597261974, lookup: 1729597261977, connect: undefined, secureConnect: undefined, upload: undefined, response: undefined, end: undefined, error: 1729597262234, abort: undefined, phases: { wait: 10, dns: 3, tcp: undefined, tls: undefined, request: undefined, firstByte: undefined, download: undefined, total: 270 } } }

**Comment by FAITH-WEN** [comment]
![Screenshot_2024-11-01-07-19-48-394_work.master.qinglongapp.jpg](https://github.com/user-attachments/assets/5dbf4bf9-9937-4206-9e9a-761af08a1778)
大佬这个啥情况，为啥会连接不上

**Comment by cyxnzb** [comment]
> ![Screenshot_2024-11-01-07-19-48-394_work.master.qinglongapp.jpg](https://private-user-images.githubusercontent.com/73750321/382139428-5dbf4bf9-9937-4206-9e9a-761af08a1778.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDQ4MTksIm5iZiI6MTczMDU0NDUxOSwicGF0aCI6Ii83Mzc1MDMyMS8zODIxMzk0MjgtNWRiZjRiZjktOTkzNy00MjA2LTllOWEtNzYxYWYwOGExNzc4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDEwNDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMjljZDdkMzIwYjRmODMxMjdmN2RiNmVkYzY0Y2MxMTIzZWEwY2NlZmJiNGRlNzBmZDMxODAxMzYyM2E4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zUfBRxbB9uKRnvgGFnghpjbgpH4Pa0eAHygglgTtP_A) 大佬这个啥情况，为啥会连接不上

跟我一样，我想可能是走tg发什么东西，发不出去导致的，因为好像是调用模块超时

**Comment by FAITH-WEN** [comment]
您好，已收到

**Comment by 6dylan6** [comment]
@cyxnzb 你这什么网络，怎么会走127ip

**Comment by cyxnzb** [comment]
> @cyxnzb 你这什么网络，怎么会走127ip

刚才又运行了一遍
这是运行结果：
调整图片中...
RequestError
    at ClientRequest.<anonymous> (/ql/data/scripts/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/ql/data/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1117:18)
    at internalConnectMultiple (node:net:1185:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1711:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1730544496180,
    socket: 1730544496183,
    lookup: 1730544496183,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1730544496434,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 0,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 254
    }
  }
}

**Comment by cyxnzb** [comment]
用的是jd云

**Comment by 6dylan6** [comment]
@cyxnzb 网络问题

**Comment by zhaobin52** [comment]
我的是这样：
开始获取商品好评和图片...
调整图片中...
write EPIPE
TypeError: Cannot read properties of undefined (reading 'code')
    at hllJqcI (/ql/data/scripts/6dylan6_jdpro_main/jd_AutoEval.js:6:75840)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_AutoEval.js:6:50247

等待5秒...

**Comment by FAITH-WEN** [comment]
您好，已收到

**Comment by cyxnzb** [comment]
> @cyxnzb 网络问题

感觉比较偶发，重装青龙后大部分时间运行是正常的，只有偶尔几次不行

**Comment by cyxnzb** [comment]
> 您好，已收到

调整图片中...
write EPIPE
TypeError: Cannot read properties of undefined (reading 'code')
    at hllJqcI (/ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:75840)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro/jd_AutoEval.js:6:50247

等待5秒...
现在是出现这个情况
