### ISSUE TITLE
京东多合一签到 报错

### ISSUE THREAD

**Issue by PHCSJC** [6dylan6/jdpro#558]
*****************开始京东账号1 aa京豆签到*******************

开始替换变量
替换变量完毕

开始执行 京东多合一签到 签到，请稍等...

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/data/scripts/6dylan6_jdpro/JDJRValidator_Pure.js
- /ql/data/scripts/6dylan6_jdpro/JD_DailyBonus.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/JDJRValidator_Pure.js:10:13)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/data/scripts/6dylan6_jdpro/JDJRValidator_Pure.js',
    '/ql/data/scripts/6dylan6_jdpro/JD_DailyBonus.js'
  ]
}

Node.js v18.12.1
京东签到脚本执行异常:Error: Command failed: /usr/bin/node ./JD_DailyBonus.js >> ./result.txt
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/data/scripts/6dylan6_jdpro/JDJRValidator_Pure.js
- /ql/data/scripts/6dylan6_jdpro/JD_DailyBonus.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/JDJRValidator_Pure.js:10:13)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/data/scripts/6dylan6_jdpro/JDJRValidator_Pure.js',
    '/ql/data/scripts/6dylan6_jdpro/JD_DailyBonus.js'
  ]
}

Node.js v18.12.1

**Comment by PHCSJC** [comment]
整点京东雨报错：

## 开始执行... 2022-12-28 17:01:00


命令未添加 "now"，随机延迟 150 秒后再执行任务，如需立即终止，请按 CTRL+C...


🔔整点京豆雨, 开始!

====================共2个京东账号Cookie=================

============脚本执行时间：2022-12-28 17:03:31=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>


本地红包雨配置获取错误，尝试从远程读取配置


今日龙王🐲出差，天气晴朗☀️，改日再来～


🔔整点京豆雨, 结束! 🕛 1.734 秒



## 执行结束...   耗时 163 秒

**Comment by PHCSJC** [comment]
京东滑块签到-加密报错：

## 开始执行... 2022-12-28 16:43:00


命令未添加 "now"，随机延迟 165 秒后再执行任务，如需立即终止，请按 CTRL+C...


🔔京东滑块签到-加密, 开始!

====================共2个京东账号Cookie=================

============脚本执行时间：2022-12-28 16:45:47=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/data/scripts/6dylan6_jdpro/jd_slider_sign.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/jd_slider_sign.js:23:1979)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/6dylan6_jdpro/jd_slider_sign.js' ]
}

Node.js v18.12.1


## 执行结束...   耗时 167 秒

**Comment by PHCSJC** [comment]
缺依赖png-js，装上就好了

**Comment by JackyKeke** [comment]
怎么样装啊 
作者没做拉库的过程吗

**Comment by Streamer-stars** [comment]
定时任务中搜索jd_indeps.sh，执行即可安装依赖
