### ISSUE TITLE
东东农场最近频繁报错

### ISSUE THREAD

**Issue by HAN915** [6dylan6/jdpro#566]
之前运行是挺好，基本不会出错，最近几天能完整跑完任务的已经没有几个了，错误日志如下。请大佬看一下

小鸭子游戏达到上限
执行再次浇水
开始检查剩余水滴能否再次浇水再次浇水

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'totalEnergy')
    at doTenWaterAgain (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:345:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async jdFruit (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:118:17)
    at async /ql/data/scripts/6dylan6_jdpro/jd_fruit.js:68:13

**Comment by HAN915** [comment]
还有，助力任务也是一直403报错，基本一圈下来没几个成功的

**Comment by dianliao** [comment]
我还以为是我的号的问题呢

**Comment by HAN915** [comment]
@dianliao   以前跑的挺好，现在助力基本是废的差不多了，浇水也老是报错
