### ISSUE TITLE
京东资产统计报错

### ISSUE THREAD

**Issue by silkiller16** [6dylan6/jdpro#584]
大佬好，这几天突然发现资产统计脚本有报错，尝试过升级ql，每天凌晨3点定时拉库，应该都已经是最新了，还是同样报错，应该如何解决？感谢！

❗️京东资产统计, 错误!
TypeError: Cannot read properties of undefined (reading 'assignmentPoints')
    at /ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:1940:34
    at got.post.then.message (/ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:3374:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by silkiller16** [comment]
> @silkiller16 更新

大佬所说的更新指的是啥？。。青龙么，还是库？。。望大佬明示= =
