### ISSUE TITLE
宠汪汪-双人赛 报错

### ISSUE THREAD

**Issue by kkwwang** [6dylan6/jdpro#587]
```
上轮比赛第一名，获得300积分！

参赛成功！

比赛信息：

❗️宠汪汪-双人赛, 错误!
TypeError: Cannot read properties of null (reading 'forEach')
    at /ql/data/scripts/6dylan6_jdpro_main/jd_joymatch.js:7:104582
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/6dylan6_jdpro_main/jd_joymatch.js:9:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by kkwwang** [comment]
估计是黑号原因，部分账号正常
