### ISSUE TITLE
依赖中的python3相关依赖全部安装失败

### ISSUE THREAD

**Issue by liugdls** [6dylan6/jdpro#590]
您好，我的青龙面板python3的依赖全部安装失败，以requests为例报错如下：

开始安装依赖 requests，开始时间 11/7/2024, 4:45:03 PM

    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip3", line 33, in <module>
    sys.exit(load_entry_point('pip==22.0.4', 'console_scripts', 'pip3')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pip3", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name

依赖安装失败，结束时间 11/7/2024, 4:45:04 PM，耗时 1.108 秒

**Comment by 6dylan6** [comment]
@liugdls 青龙坏了 吧。重新装个试试吧

**Comment by liugdls** [comment]
好的，我试下，谢谢！
