### ISSUE TITLE
带图评价用不了了，已经安装了sharp依赖

### ISSUE THREAD

**Issue by zhaobin52** [6dylan6/jdpro#619]
开始获取商品好评和图片...
调整图片中...
write EPIPE
TypeError: Cannot read properties of undefined (reading 'code')
    at hllJqcI (/ql/data/scripts/6dylan6_jdpro_main/jd_AutoEval.js:6:75840)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_AutoEval.js:6:50247

等待5秒...

**Comment by zhqqqy** [comment]
+1

**Comment by deawii** [comment]
+2

**Comment by Felix-yao** [comment]
+1

**Comment by OwnerCM** [comment]
+1

**Comment by paigu01** [comment]
+3

**Comment by paigu01** [comment]
更新最新版青龙面板就好了
