### ISSUE TITLE
新农场运行一半报错，之前没有问题

### ISSUE THREAD

**Issue by wangjing71** [6dylan6/jdpro#629]
使用代理IP：60.177.207.119:15943
非法请求：1秒内提取IP数量达到上限。请稍后再试或购买更多套餐
非法请求：1秒内提取IP数量达到上限。请稍后再试或购买更多套餐
RequestError: connect ECONNREFUSED 47.93.36.21:443
    at ClientRequest.<anonymous> (/ql/node_modules/.pnpm/got@11.8.3/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/ql/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1733193639030,
    socket: 1733193639030,
    lookup: 1733193639193,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1733193639222,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 163,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 192
    }
  }
}
TypeError: Cannot read properties of undefined (reading 'body')
    at W9pDbu8 (/ql/scripts/6dylan6_jdpro/function/proxy.js:1:52253)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ciZckw (/ql/scripts/6dylan6_jdpro/function/proxy.js:1:62643)
    at async ddd (/ql/scripts/6dylan6_jdpro/function/proxy.js:1:67568)
    at async /ql/scripts/6dylan6_jdpro/function/proxy.js:1:70824

## 执行结束... 2024-12-03 10:40:39 耗时 1839 秒

**Comment by 6dylan6** [comment]
@wangjing71 你看提示呀，非法请求：1秒内提取IP数量达到上限，你代理顶不住，

**Comment by wangjing71** [comment]
浇水第77次
浇水10g成功,剩余1057g，再浇84.89%收获！

浇水第78次
HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/ql/node_modules/.pnpm/got@11.8.3/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1733206679780,
    socket: 1733206679780,
    lookup: 1733206679930,
    connect: 1733206679956,
    secureConnect: 1733206679987,
    upload: 1733206679987,
    response: 1733206680014,
    end: 1733206680015,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 150,
      tcp: 26,
      tls: 31,
      request: 0,
      firstByte: 27,
      download: 1,
      total: 235
    }
  }
}
TypeError: Cannot read properties of undefined (reading 'body')
    at W9pDbu8 (/ql/scripts/6dylan6_jdpro/function/proxy.js:1:52253)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ciZckw (/ql/scripts/6dylan6_jdpro/function/proxy.js:1:62643)
    at async ddd (/ql/scripts/6dylan6_jdpro/function/proxy.js:1:67568)
    at async /ql/scripts/6dylan6_jdpro/function/proxy.js:1:70824

## 执行结束... 2024-12-03 14:18:00 耗时 2100 秒

**Comment by wangjing71** [comment]
感觉不是代理问题，上个版本就没这个问题，更新了最新版本才出现的。。

**Comment by 6dylan6** [comment]
@wangjing71 你不用代理试试，农场没必要代理
