### ISSUE TITLE
批量取关店铺和商品异常

### ISSUE THREAD

**Issue by yuhui0928** [6dylan6/jdpro#669]
正在获取已关注的商品...

❗️批量取关店铺和商品, 错误!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /ql/data/scripts/6dylan6_jdpro/jd_unsubscribe.js:225:29
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/6dylan6_jdpro/jd_unsubscribe.js:659:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
不执行取消收藏商品

**Comment by 6dylan6** [comment]
已修复

**Comment by yuhui0928** [comment]
谢谢
