### ISSUE TITLE
QQ星系牧场, 错误

### ISSUE THREAD

**Issue by JackHe455** [6dylan6/jdpro#682]
❗️QQ星系牧场, 错误!
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
at JSON.parse ()
at /ql/data/scripts/6dylan6_jdpro/jd_qqxing.js:10:77244
at got.post.then.message (/ql/data/scripts/6dylan6_jdpro/jd_qqxing.js:11:5772)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
可兑换 0 次 20京🐶
很遗憾，商品已兑换光～

❗️QQ星系牧场, 错误!
TypeError: $[_0x49d490] is not iterable
at /ql/data/scripts/6dylan6_jdpro/jd_qqxing.js:10:35495
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

🔔QQ星系牧场, 结束! 🕛 51.875 秒

**Comment by 6dylan6** [comment]
@JackHe455 测试正常，换个时间在运行看看
