### ISSUE TITLE
拆快递脚本有bug

### ISSUE THREAD

**Issue by necan** [6dylan6/jdpro#719]
四个账号，只有两个用脚本能正常运行，号都没有黑，在手机上能手动完成任务。

******开始【京东账号1】xxx*********

无内容
当前 总计已拆220 个快递！
今年已拆19/36
有可领红包...
undefined
TypeError: Cannot read properties of null (reading 'gradeAwardVo')
    at _0x48bcec (/ql/data/scripts/shufflewzc_faker2_main/jd_618ckd.js:9:216780)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/shufflewzc_faker2_main/jd_618ckd.js:9:207052

去做微信小程序任务

**Comment by 6dylan6** [comment]
@necan 更新试试

**Comment by ntbzx** [comment]
<img width="455" alt="image" src="https://github.com/6dylan6/jdpro/assets/27877221/5b309c8f-af96-41dd-8845-5a48af85207d">
是不是不能用啦
