### ISSUE TITLE
JDJRValidator_Pure.js无法验证图片报错

### ISSUE THREAD

**Issue by scottuu** [6dylan6/jdpro#76]
JDJR验证中......
evalmachine.<anonymous>:1
<!DOCTYPE html>
[evalmachine.<anonymous>:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInContext (node:vm:288:10)
    at IncomingMessage.<anonymous> (C:\Users\JD\Documents\JD_main\JDJRValidator_Pure.js:350:16)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
evalmachine.<anonymous>:1
<!DOCTYPE html>
SyntaxError: Unexpected token '<'
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInContext (node:vm:288:10)
    at IncomingMessage.<anonymous> (C:\Users\JD\Documents\JD_main\JDJRValidator_Pure.js:350:16)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

❌ 宠汪汪喂食, 失败! 原因: TypeError: Cannot read property 'validate' of undefined!

**Comment by 6dylan6** [comment]
@scottuu 坏了，已删

**Comment by scottuu** [comment]
宠汪汪的都不更新了吗？
