### ISSUE TITLE
依赖安装报错

### ISSUE THREAD

**Issue by OldCoding** [6dylan6/jdpro#8]
运行依赖安装任务，最后两个依赖可能没安装上，日志最后显示如下
青龙版本是2.15.15
Done in 12.9s
Progress: resolved 326, reused 304, downloaded 0, added 0, done
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'

**Comment by OldCoding** [comment]
![image](https://github.com/6dylan6/jdpro/assets/85047508/2ece02f4-7517-448d-80af-bdcee411fe97)
手动复制命令安装也报错

**Comment by OldCoding** [comment]
手动安装pip后解决了
