### ISSUE TITLE
执行错误

### ISSUE THREAD

**Issue by yuanch1** [6dylan6/jdpro#8]
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/scripts/dylanote_jdpro/jd_ms.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.initGotEnv (/ql/scripts/dylanote_jdpro/jd_ms.js:411:3796)
    at Object.post (/ql/scripts/dylanote_jdpro/jd_ms.js:411:5658)
    at /ql/scripts/dylanote_jdpro/jd_ms.js:357:7
    at new Promise (<anonymous>)
    at TotalBean (/ql/scripts/dylanote_jdpro/jd_ms.js:343:10)
    at /ql/scripts/dylanote_jdpro/jd_ms.js:52:13 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/dylanote_jdpro/jd_ms.js' ]
}

**Comment by 6dylan6** [comment]
缺这依赖真不常见，pnpm install -g tough-cookie

**Comment by yuanch1** [comment]
谢谢佬，缺其他库也是执行这样的类似命令嘛
