### ISSUE TITLE
农场任务出现下面错误

### ISSUE THREAD

**Issue by Dec-QXY** [6dylan6/jdpro#80]
❗️东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'code')
    at _0x1d29cd (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:19:65953)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x282081 (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:19:27995)
    at async _0x3abd56 (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:19:17077)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:19:11857
    
在运行到第二个账号的时候出现这种错误

**Comment by 6dylan6** [comment]
@Dec-QXY 更新没有。

**Comment by Dec-QXY** [comment]
我状态晚上21点才拉的库 今天发现后面的几个账号出现下面的问题
❗️东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'remainLotteryTimes')
    at _0x1d29cd (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:19:68829)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x282081 (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:19:27995)
    at async _0x3abd56 (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:19:17077)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:19:11857
    还有一些
    initForFarm: 请求失败 ‼️‼️
"getaddrinfo EAI_AGAIN api.m.jd.com"
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: ""这个问题，账号没有问题，app中能打开

**Comment by 6dylan6** [comment]
@Dec-QXY 你网络问题

**Comment by Dec-QXY** [comment]
前面几个账号是可以的，会不会是因为请求太频繁的原因

**Comment by 6dylan6** [comment]
@Dec-QXY 你延迟默认的5s吗 ，调大点试试吧

**Comment by Dec-QXY** [comment]
## 默认给javascript任务加随机延迟，如 RandomDelay="300" ，表示任务将在 1-300 秒内随机延迟一个秒数，然后再运行，取消延迟赋值为空
RandomDelay="100"
这里我设置的100，我使用的家用网络也会出现网络的问题嘛

**Comment by 6dylan6** [comment]
@Dec-QXY ？看脚本注释。和RandomDelay这没关系啊。你改它干嘛

**Comment by Dec-QXY** [comment]
解决了 谢谢
