### ISSUE TITLE
京东种豆得豆, 错误!

### ISSUE THREAD

**Issue by yum-sky** [6dylan6/jdpro#87]
bug:
```
❗️京东种豆得豆, 错误!
TypeError: goodShopList is not iterable
    at doTask (/ql/scripts/6dylan6_jdpro/jd_plantBean.js:259:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async jdPlantBean (/ql/scripts/6dylan6_jdpro/jd_plantBean.js:110:7)
    at async /ql/scripts/6dylan6_jdpro/jd_plantBean.js:68:7
```
临时解决方法：
jd_plantBean.js 259行 解构赋值设置一个默认值
258行改为 const { goodShopList = [], moreShopList = [] } = data;

**Comment by 6dylan6** [comment]
更新
