### ISSUE TITLE
农场和种豆得豆报这个错是啥问题呀？

### ISSUE THREAD

**Issue by Sardine97** [6dylan6/jdpro#87]
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './function/dylany'
Require stack:
- /ql/data/scripts/6dylan6_jdpro/jd_fruit.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:19:3043)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/6dylan6_jdpro/jd_fruit.js' ]
}

Node.js v18.17.1

**Comment by Sardine97** [comment]
解决了是因为dylany这个模块失效被删除了，重新拉库就好了

**Comment by weixin2304** [comment]
请问下我重新去拉库了，执行是还是提示一样的错误，这个要怎么解决？

## 开始执行... 2023-10-10 23:20:12


🔔东东农场-任务, 开始!
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './function/dylany'
Require stack:
- /ql/data/scripts/6dylan6_jdpro/jd_fruit.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/jd_fruit.js:21:4720)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/6dylan6_jdpro/jd_fruit.js' ]
}

Node.js v18.17.1

## 执行结束... 2023-10-10 23:20:17  耗时 5 秒

**Comment by 6dylan6** [comment]
@weixin2304 拉库不全，检查配置
