### ISSUE TITLE
task 6dylan6_jdpro/jd_m_sign.js failed

### ISSUE THREAD

**Issue by zgca** [6dylan6/jdpro#88]
签到开始........
失败：00017_jingbean incomeBeans threshold error!
失败：0010_exceed pool balance
TypeError: Cannot read properties of null (reading '1')
    at /ql/scripts/6dylan6_jdpro/jd_m_sign.js:95:81
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/6dylan6_jdpro/jd_m_sign.js:231:5721)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by 6dylan6** [comment]
更新了
