### ISSUE TITLE
618红包jd_getred.js报错

### ISSUE THREAD

**Issue by kokpk** [6dylan6/jdpro#9]
/usr/local/pnpm-global/5/node_modules/.pnpm/registry.npmmirror.com+jsdom@22.1.0/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:583
      this[filesSymbol] ||= FileList.createImpl(this._globalObject);
                        ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/registry.npmmirror.com+jsdom@22.1.0/node_modules/jsdom/lib/jsdom/living/generated/HTMLInputElement.js:1875:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

请问报这个错误是什么原因，怎么修复。谢谢

**Comment by 6dylan6** [comment]
@kokpk 依赖问题，重新安装jsdom试试

**Comment by kokpk** [comment]
请问这个怎么重装？我删除了/usr/local/pnpm-global/5/node_modules里的jsdom然后青龙面板依赖管理NodeJs里添加jsdom后还是报错。
/usr/local/lib/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:583
      this[filesSymbol] ||= FileList.createImpl(this._globalObject);
                        ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/jsdom/lib/jsdom/living/generated/HTMLInputElement.js:1875:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by kokpk** [comment]
> @kokpk 依赖问题，重新安装jsdom试试

QL版本是2.10.13

**Comment by kokpk** [comment]
我npm install jsdom@18.0.0 -g 降级后可以跑了。。

**Comment by kokpk** [comment]
最新的 jsdom 是不是要node也是最新的才可以跑？QL2.10.13怎么升级node至最新呢？

**Comment by 6dylan6** [comment]
@kokpk 可能是吧
