### ISSUE TITLE
找不到模块

### ISSUE THREAD

**Issue by XQlingss** [6dylan6/jdpro#90]
Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/scripts/dylanote_jdpro/jx_products_detail.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.initGotEnv (/ql/scripts/dylanote_jdpro/jx_products_detail.js:112:3082)
    at Object.get (/ql/scripts/dylanote_jdpro/jx_products_detail.js:112:3659)
    at /ql/scripts/dylanote_jdpro/jx_products_detail.js:54:11
    at new Promise (<anonymous>)
    at getCommodityList (/ql/scripts/dylanote_jdpro/jx_products_detail.js:53:12)
    at /ql/scripts/dylanote_jdpro/jx_products_detail.js:24:19

**Comment by XQlingss** [comment]
是不是缺少依赖库  依赖库怎么安装 我看没有你写的那个脚本jd_indeps

**Comment by vadonmo** [comment]
> 是不是缺少依赖库 依赖库怎么安装 我看没有你写的那个脚本jd_indeps

仔细看文档，改配置文件添加sh后缀

**Comment by 6dylan6** [comment]
## ql repo命令拉取脚本时需要拉取的文件后缀，直接写文件后缀名即可
RepoFileExtensions="js py sh"
