### ISSUE TITLE
东东农场-任务, 错误!TypeError: Cannot read properties of undefined (reading 'totalEnergy')

### ISSUE THREAD

**Issue by hackgsl** [6dylan6/jdpro#92]
❗️东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'totalEnergy')
    at _0x7bf86f (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:20:66472)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x2b5ff6 (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:20:27051)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:20:14154

**Comment by hackgsl** [comment]
9.8的版本，第一个
【首次浇水奖励】获得5g💧
10次浇水 未完成，今日浇水5次
finished 水果任务完成!
任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场-任务, 错误!
TypeError: Cannot destructure property 'waterFriendCountKey' of '$[_0x5bc161(...)][_0x10747f(...)]' as it is undefined.
    at _0x3a82cb (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:20:130976)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x2b5ff6 (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:20:27213)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:20:14154

**Comment by hackgsl** [comment]
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ2RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"degradeConfig":null,"code":"0","bizCode":null,"idCertification":{"status":0},"rightUpResouces":{"advertId":"1801768217","name":"右上角icon","appImage":"https://m.360buyimg.com/babel/jfs/t1/121719/24/38422/8363/64eea6aeF7903f500/a94c4a9eb83139bd.png","appLink":"https://pro.m.jd.com/mall/active/4P9a2T9osR9JvtzHVaYTPvsecRtg/index.html?babelChannel=ttt52","cxyImage":"https://m.360buyimg.com/babel/jfs/t1/121719/24/38422/8363/64eea6aeF7903f500/a94c4a9eb83139bd.png","cxyLink":"https://pro.m.jd.com/mall/active/4P9a2T9osR9JvtzHVaYTPvsecRtg/index.html?babelChannel=ttt52","type":"","openLink":false,"channelType":"all"},"turntableInit":{"timeState":1},"showExchangeGuidance":false,"waterGiftSurpriseIconLink":null,"mengchongResouce":{"advertId":"4401733040","name":"左下角鸭子icon放萌宠","appImage":"https://m.360buyimg.com/babel/jfs/t1/145092/37/18785/14059/5fd9f2bcEd3d080f7/57784b97834ebcb8.gif","appLink":"https://h5.m.jd.com/rn/42yjy8na6pFsq1cx9MJQ5aTgu3kX/index.html?has_native=0&source=nongchanghome3","cxyImage":"","cxyLink":"","type":"","openLink":false,"channelType":"app"},"clockInGotWater":true,"isOpenOldRemind":false,"guidPopupTask":{"guidPopupTask":"none"},"toFruitEnergy":50,"h5ShieldConfig":{"jump":false,"jumpType":0},"couponSurpriseIconLink":null,"statisticsTimes":null,"sysTime":1694460882168,"canHongbaoContineUse":false,"shareChannelType":1,"toFlowTimes":20,"iosConfigResouces":{"advertId":"8901754379","name":"天天红包","appImage":"https://m.360buyimg.com/babel/jfs/t1/84486/39/23156/16413/645b6b48Fc54028e7/96a53b601cbd3717.png","appLink":"https://carry.m.jd.com/babelDiy/Zeus/CvMVbdFGXPiWFFPCc934RiJfMPu/index.html?babelChannel=ttt1","cxyImage":"","cxyLink":"","type":"","openLink":false,"channelType":""},"assistPageType":1,"todayGotWaterGoalTask":{"canPop":false},"leftUpResouces":null,"minSupportAPPVersion":"8.5.4","lowFreqStatus":0,"funCollectionHasLimit":false,"message":null,"treeState":1,"rightDownResouces":{"advertId":"1201844348","name":"风车","appImage":"https://m.360buyimg.com/babel/jfs/t1/101848/16/43657/8746/64fab373F88398c31/ec025a9183e65dab.png","appLink":"https://pro.m.jd.com/mall/active/3iXU1kvcZaGz6Xf9L3cJ9aCS6ShN/index.html?has_native=0&jwebprog=0&hybrid_err_view=1&ad_od=1&transparent=1&babelChannel=ttt65","cxyImage":"https://m.360buyimg.com/babel/jfs/t1/101848/16/43657/8746/64fab373F88398c31/ec025a9183e65dab.png","cxyLink":"https://pro.m.jd.com/mall/active/3iXU1kvcZaGz6Xf9L3cJ9aCS6ShN/index.html?has_native=0&jwebprog=0&hybrid_err_view=1&ad_od=1&transparent=1&babelChannel=ttt65","type":"H5","openLink":true,"channelType":"all"},"initExtInfo":{"backgroundPicUrl":"https://m.360buyimg.com/babel/jfs/t1/116882/19/28687/186109/637dc629E3c5df377/de2213a580ffe1a1.jpg","waterwheelPic":"https://m.360buyimg.com/babel/jfs/t1/184263/35/30976/22341/63772685E5a430941/5a7327a21e85a87c.png"},"toFlowEnergy":40,"farmUserPro":{"totalEnergy":24,"treeState":1,"groupSkuId":"10190616-54349018133","createTime":1567142465000,"treeEnergy":520,"treeTotalEnergy":6000,"shareCode":"4ef84cd7ae91481a8540efc29da8b970","winTimes":24,"nickName":"如英","imageUrl":"https://storage.360buyimg.com/user.headphoto.v1/st-HGG5gj8TimMFI5wTXaCc9","couponKey":"vender_BA#aee8ad782bbd4b23a2aa3d5c9a4ad3b3","type":"boluo","simpleName":"菠萝约1.5斤","name":"菠萝约1.5斤","goodsImage":"https://m.360buyimg.com/babel/jfs/t1/111203/6/39337/78511/64b7aafdF5dc4078f/0f7845e862b3ef1a.jpg","skuId":"10078754871886","lastLoginDate":1694452305000,"newOldState":4,"oldMarkComplete":0,"commonState":31,"prizeLevel":2},"retainPopupLimit":1,"toBeginEnergy":30,"collectPopWindow":{"windowType":3,"type":2,"invitePicUrl":"https://m.360buyimg.com/babel/jfs/t1/180504/11/4736/189987/60a33534Eb63e8ae9/aae12f1665e7e73c.png","inviteLinkUrl":"https://h5.m.jd.com/babelDiy/Zeus/J1C5d6E7VHb2vrb5sJijMPuj29K/index.html?babelChannel=ttt1","iconUrl":"https://m.360buyimg.com/babel/jfs/t1/188599/35/13234/51145/60efe307Efd216561/60d98dbc9ae80fce.gif","userLevel":-1},"leftDownResouces":null,"enableSign":false,"loadFriend":{"code":"0","bizCode":null,"statisticsTimes":null,"sysTime":1694460882148,"message":null,"firstAddUser":false},"hadCompleteXgTask":false,"groupGiftSurpriseIconLink":null,"oldUserIntervalTimes":[7,7,14,14,21],"toFruitTimes":59,"oldUserSendWater":["108","128","108","128","108","128","108","128","108","128"]}

**Comment by hackgsl** [comment]
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ2RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"code":"6","bizCode":null,"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"enableSign":false,"sysTime":1694460888789,"minSupportAPPVersion":"8.5.4","message":null}
