### ISSUE TITLE
京东多合一签到报错

### ISSUE THREAD

**Issue by liuze0109** [6dylan6/jdpro#94]
## 开始执行... 2022-03-22 16:55:36

🔔京东多合一签到, 开始!

====================共1个京东账号Cookie=================

============脚本执行时间：2022/3/22 16:55:36=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

*****************开始京东账号1 御用口香糖京豆签到*******************

开始替换变量
替换变量完毕

开始执行 京东多合一签到 签到，请稍等...

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js
- /ql/scripts/6dylan6_jdpro/JD_DailyBonus.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js:10:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js',
    '/ql/scripts/6dylan6_jdpro/JD_DailyBonus.js'
  ]
}

Node.js v17.5.0
京东签到脚本执行异常:Error: Command failed: /usr/local/bin/node ./JD_DailyBonus.js >> ./result.txt
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js
- /ql/scripts/6dylan6_jdpro/JD_DailyBonus.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js:10:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/6dylan6_jdpro/JDJRValidator_Pure.js',
    '/ql/scripts/6dylan6_jdpro/JD_DailyBonus.js'
  ]
}

Node.js v17.5.0

🔔京东多合一签到, 结束! 🕛 1.269 秒

## 执行结束... 2022-03-22 16:55:37 耗时 1 秒

**Comment by sunxiaozhi** [comment]
这个怎么解决的？
