### ISSUE TITLE
请问执行任务报这个错误如何解决

### ISSUE THREAD

**Issue by huang770101** [6dylan6/jdpro#96]
sign获取失败,重试...

Timeout awaiting 'lookup' for 100ms
sign获取失败,请检查网络！

TypeError: Cannot read properties of undefined (reading 'body')
    at Object._0x30bb24 [as getbody] (/ql/scripts/6dylan6_jdpro/function/dylanx.js:1:19285)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _0xd4c415 (/ql/scripts/6dylan6_jdpro/function/dylank.js:1:38208)
    at async _0x415722 (/ql/scripts/6dylan6_jdpro/jd_dplh0915.js:20:18621)
    at async /ql/scripts/6dylan6_jdpro/jd_dplh0915.js:20:12888
Token请求失败
❌ 获取TOKEN失败

**Comment by 6dylan6** [comment]
@huang770101 重试看看，网络正常吗

**Comment by huang770101** [comment]
网络正常的，其他脚本都可以用就是头文字jjj和中秋礼遇 酒等你来这些新的不可以

**Comment by 6dylan6** [comment]
@huang770101 再更新试试
